### ISSUE TITLE
config.json can't load 

### ISSUE THREAD

**Issue by gdtiti** [DominikDoom/a1111-sd-webui-tagcomplete#1]
http://127.0.0.1:7860/file/tags/config.json 500 internal server error

**Comment by DominikDoom** [comment]
Did you place the file in the right spot? I tested it on Chrome and Firefox just now and it still works for me.

**Comment by evanjs** [comment]
I'm seeing a similiar issue with any files specified in `wc.txt`.

The `wc.txt` file appears to initialize as expected, but reads for the specified files seem to fail.

It looks like there is some sandboxing, and only certain files are allowed to load, as far as I can tell.

```
ValueError: File cannot be fetched: scripts/wildcards/views.txt, perhaps because it is not in any of
{'C:\\Users\\evanjs\\AppData\\Local\\Temp\\tmp1z27z66v', 'C:\\Users\\evanjs\\AppData\\Local\\Temp\\tmpfnroftve', ... }
```

Source of upstream error:
https://github.com/gradio-app/gradio/blob/831ae1405f0f2cddf8d508775731eef39c5a09df/gradio/routes.py#L253-L256

**Comment by DominikDoom** [comment]
Yes, Gradio for security reasons only allows to load files in the app root and its subdirectories via JavaScript. But everything in the wildcards folder should be fine under that condition.
Are you running the webui from a different location or something like that?

**Comment by evanjs** [comment]
Thanks for the 🦆, that makes sense now.
I have wildcards stored somewhere external to the webui, and that is what was causing issues on my end.
Ensuring any/all symlinks point to a directory within the application root ensures that the wildcard files can be loaded properly.

**Comment by DominikDoom** [comment]
Since the original issue was ages ago before the extension system, and the OP has not provided feedback, closing the issue for now.
