### ISSUE TITLE
it doesnt work after new update a1111.

### ISSUE THREAD

**Issue by hungrydog666** [DominikDoom/a1111-sd-webui-tagcomplete#105]
i tried reinstal and instal it again but it doesnt work. why???

**Comment by DominikDoom** [comment]
Make sure your webui is also up to date.
If that doesn't solve it for you I'll need more info.

**Comment by Fresh-glitch** [comment]
My WebUI is up to date, they recently changed the UI causing this extension to not work anymore. There are no error messages.

**Comment by Fresh-glitch** [comment]
Nvm I fixed it, just needed to disable the extension, restart, and then enable it again.

**Comment by hungrydog666** [comment]
> Nvm I fixed it, just needed to disable the extension, restart, and then enable it again.

i re instal SD because somehow it lagging but now it work.
