### ISSUE TITLE
with today's a1111 webui update the program has stopped working

### ISSUE THREAD

**Issue by Dravoss** [DominikDoom/a1111-sd-webui-tagcomplete#113]
The extension does not load and it does not appear in webui not showing the autocomplete dialogue.

**Comment by DominikDoom** [comment]
I can't reproduce this, it is still working for me on webui commit [6faae232](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/6faae2323963f9b0e0086a85b9d0472a24fbaa73), which is the most recent one.
![image](https://user-images.githubusercontent.com/34448969/213205353-8afe5cf8-0dcc-4843-b3e6-5de4b9779f21.png)

Can you give me some more details? What browser are you using, are there any errors in the webui terminal or your browser console?

**Comment by Dravoss** [comment]
I was getting an "Exception in ASGI application" error at launch, disabling this extension got rid of it.

**Comment by DominikDoom** [comment]
Any other extensions active? Also would be a great help if you can send the error message or a screenshot of it here.

**Comment by Dravoss** [comment]
I think it is because i installed this in the early days with the old manual method and it never got updated, i am going to try to uninstall and reinstall it as an extension, i will report back.

**Comment by Dravoss** [comment]
I was right and now it is working, i was unaware of it not updating and they changed something at a1111 webui that made the old tagcomplete version to return the error. Thank you for your help. Also i prefer the settings at the settings tab over the check boxes at the txt2img one (yes my version was that old) (U-_-) .

**Comment by DominikDoom** [comment]
No problem, thanks for letting me know the old method doesn't work anymore.
After the change to support extensions last year I never really tried that one again, extensions are much more convenient.

I'll update the readme to include a note about it.

**Comment by DominikDoom** [comment]
Well, could be both, but since I don't really plan to support the outdated installation method anyway, it doesn't hurt to remove it.
