### ISSUE TITLE
I noticed that under current WebUI versions (about a week old till yesterday, today not tested yet), this extension just being active freezes the whole browser tab.

### ISSUE THREAD

**Issue by mart-hill** [DominikDoom/a1111-sd-webui-tagcomplete#118]
I noticed that behavior a couple of days back, and only disabling/removing the extension helped. Last time I tested that was yesterday.
There's only a very slight "window" between "chokes" of the whole tab in the browser (100% of one CPU thread), when/where I was able to change tab, for example, or try to check for extension updates (which usually won't work, since whole Javascript seems to be frozen for a moment). Ultimately, even the "Apply and restart" button didn't finish, and I had to kill the .bat execution and close the tab.
It happened shortly after WebUI introduced a change in syntax and parenthesis/tokens counting/checking in both prompt and anti-prompt fields. 
It could be a "ripple" with another extension as well though.

**Comment by DominikDoom** [comment]
This does not happen to me on the newest version or before that. It is also (likely) unrelated to webui changes, since the autocomplete script is mostly javascript, so client side. Changes to the token counting or parentheses don't impact the method I use, it is purely based on listening to text changes in the prompt fields.

Can you send me a screenshot of your autocomplete settings page?

**Comment by mart-hill** [comment]
I did uninstall the whole extension, so I don't have the part of it in the WebUI config. I can deliver the config though. 
I reinstalled the extension from the scratch, and still got the freeze, and on every browser I tried (Chrome, Brave, MS Edge and Firefox). The only "common denominator" is active AdGuard software (not an extension, but the software), I disabled localhost filtering though and your extension worked (it's very helpful!) even with it actively filtering 127.0.0.1. Other one is Comodo Internet Security, but it wasn't an issue either before this happened.

I just reinstalled the extension from the fresh, and got the message from Edge about "not responding" tab. I'll try to go to config section nonetheless. 🙂

**Comment by DominikDoom** [comment]
Yeah it's like I suspected, "extra file" at the bottom is at fault here. This feature is only meant for small additions, like custom aliases or new additions for user defined tags. If you give it e621, danbooru or really any big csv file there, it will do a search of the whole list for each entry to potentially add an alias to. Meaning in your case it will do 100k^2 = 10.000.000.000 lookups.

Just choose None there and it should load faster again.

**Comment by mart-hill** [comment]
Oh my, 10 billion?? In JavaScript? 
If and when I take control of the WebUI - gotta turn it off! 🙂

**Comment by mart-hill** [comment]
Is it possible to "delegate" this lookup to a different thread inside the browser tab sandbox?

**Comment by DominikDoom** [comment]
Well, the warning about e621 was added because this was a "common" mistake. Most people use danbooru as their main file and didn't realize that e621 isn't meant as an extra but a whole main tag file on its own.

Really I should rework the extra system all together, it's a relic from the first way tag translations were implemented.

**Comment by mart-hill** [comment]
Thank you so much for your time and for the hint - I'll try to fix it on my side either within the UI or in config, here:

```
    "tac_tagFile": "danbooru.csv",
    "tac_active": true,
    "tac_activeIn.txt2img": true,
    "tac_activeIn.img2img": true,
    "tac_activeIn.negativePrompts": true,
    "tac_maxResults": 5.0,
    "tac_showAllResults": false,
    "tac_resultStepLength": 100.0,
    "tac_delayTime": 100.0,
    "tac_useWildcards": true,
    "tac_useEmbeddings": true,
    "tac_replaceUnderscores": true,
    "tac_escapeParentheses": true,
    "tac_appendComma": true,
    "tac_alias.searchByAlias": true,
    "tac_alias.onlyShowAlias": false,
    "tac_translation.translationFile": "None",
    "tac_translation.oldFormat": false,
    "tac_translation.searchByTranslation": true,
    **"tac_extra.extraFile": "danbooru.csv",** <- here, right? "None"? :)
    "tac_extra.onlyAliasExtraFile": false,
```

**Comment by DominikDoom** [comment]
Correct, "None" there should do the trick. Like translation file above it.

The use case of extra files is definitely there, e.g. for adding shorthands for common tags or mini-prompts using an alias, or adding "quality tags" like NAI and WD use. But I'm pretty sure after a recent change in how I parse and order tags this will be doable without comparing to the original list. So the rework is long overdue.

**Comment by mart-hill** [comment]
Thank you for your hard work! It's certainly not easy to write such a parser.
