### ISSUE TITLE
[Feature Request] Automatically initialize wildcard list

### ISSUE THREAD

**Issue by horribleCodes** [DominikDoom/a1111-sd-webui-tagcomplete#12]
The wildcard embedding works great, but is it possible for the available wildcard lists to be located by looking through the directory? I can't really think of a reason why you would not want a list to show up, and it makes adding a bunch of lists more of a hassle.

**Comment by horribleCodes** [comment]
Ah, reading #8, I see that it actually isn't possible to check directories - a shame, then.

**Comment by DominikDoom** [comment]
Yeah, I sadly can't do that with JavaScript only. The only thing I've thought of would be a companion .py script that goes into the normal scripts folder, scans the folders, and writes the content to a temporary file the javascript side can then load. I might experiment with that approach a bit, but in the meantime the manual list is the only way.

**Comment by DominikDoom** [comment]
Automatic wildcard and embed discovery is now supported by using a python helper script!
It scans the directories and saves those filenames in /tags/temp/, so as of 08c10928f8618913260effacfcb28f05437f13db you don't need the manually created wildcardNames list anymore.

**Comment by horribleCodes** [comment]
Great, thanks!
