### ISSUE TITLE
wildcards tag completion don't show

### ISSUE THREAD

**Issue by imthejuaum** [DominikDoom/a1111-sd-webui-tagcomplete#13]
hi, i'm a new using this and i don't have much knowledge of this. so, i write: "long hair, __" but nothing appear
![a](https://user-images.githubusercontent.com/115851023/195962772-365db14e-41b9-430f-9abe-71bd816f9757.png)

**Comment by DominikDoom** [comment]
Wildcards are disabled by default since not everyone has that script. To use them, you need to edit config.json and set "useWildcards" to true. You also need to add/uncomment the name of every wildcard file you want to use in the wildcardNames.txt file.

**Comment by 4meame** [comment]
Still not show, I set "useWildcards" to true.

**Comment by DominikDoom** [comment]
I recently pushed a new version that makes it easier to add wildcards, please update and try again.
It should be enabled by default now and scan the folder for wildcard files automatically.
So all you need to do is have the wildcard files you want to use in the `/scripts/wildcards/` folder

**Comment by 4meame** [comment]
Well done dude.I exactly saw the scanned txt in the temp text,but it dose still not show wc tag.I guess maybe "two underscores" doesn't work, can I change the way?

**Comment by 4meame** [comment]
> Well done dude.I exactly saw the scanned txt in the temp text,but it dose still not show wc tag.I guess maybe "two underscores" doesn't work, can I change the way?

or configure the way ?

**Comment by sgmklp** [comment]
try this
![image](https://user-images.githubusercontent.com/74038035/195990755-b01aac4b-97bb-4dad-bf96-e90240f50281.png)

**Comment by 4meame** [comment]
I find some clues,it works in Chrome but Firefox not.

**Comment by DominikDoom** [comment]
It works for me in Firefox, so I think it might be a cache issue.
Try clearing your browser cache or opening the Developer Tools and disabling cache in the "Network" tab before reloading the page.

**Comment by 4meame** [comment]
> It works for me in Firefox, so I think it might be a cache issue. Try clearing your browser cache or opening the Developer Tools and disabling cache in the "Network" tab before reloading the page.

Thank you,finally :>

**Comment by DominikDoom** [comment]
Glad I could help!

**Comment by sgmklp** [comment]
and you can just use the CTRL+F5
