### ISSUE TITLE
Escape key unfocuses textarea in Firefox

### ISSUE THREAD

**Issue by Kenqr** [DominikDoom/a1111-sd-webui-tagcomplete#133]
In Firefox, if you press escape key when focusing a textarea, it will lose focus.
I guess calling `event.preventDefault()` would fix this problem.

**Comment by DominikDoom** [comment]
As you can see here, this is already the case:
https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/blob/d1fff7bfa70bb58200464aa185b7ca8383538a17/javascript/tagAutocomplete.js#L775

Also, I can't reproduce what you said, it doesn't happen to me on Firefox 110.0.1 and stays focused after the window closes. As a matter of fact, I can't even get it to lose textbox focus at all by pressing escape, even if the completion window is closed.

**Comment by Kenqr** [comment]
Sorry, I think it is because I have Vimium installed.
Adding my webui URL to the excluded URL list solved the problem.
