### ISSUE TITLE
Pop not showing up for regular tags

### ISSUE THREAD

**Issue by luojiesi** [DominikDoom/a1111-sd-webui-tagcomplete#135]
I just installed this extension under the latest chrome. I was able to get the pop up showing up correctly for embeddings/lora etc.. It also works if I type '__'. However, the pop up is not showing up for regular tags. For example, if I type 'qua', nothing shows up. I am expecting a suggestion on 'quality'.

**Comment by DominikDoom** [comment]
That sounds to me like the main tag file wasn't loaded correctly for some reason.
Do you have any errors in your browser console or network tab?

I also know of a problem that can happen if another extension tries to request too many files in a short period, Chrome will block these "spam" requests and not try to reload them later, so it could block my files from loading if it starts loading around the same time. But that would be visible in the browser console too, so really that's the best starting point to look.

**Comment by luojiesi** [comment]
Thanks for the lead. Let me look into it.

**Comment by PuDood** [comment]
> That sounds to me like the main tag file wasn't loaded correctly for some reason.在我看来，由于某种原因，主标记文件没有正确加载。在我看来，由于某种原因，主标记文件没有正确加载 在我看来，由于某种原因，主标记文件没有正确加载。  Do you have any errors in your browser console or network tab?您的浏览器控制台或网络选项卡中有任何错误吗？您的浏览器控制台或网络选项卡中有任何错误吗 您的浏览器控制台或网络选项卡中有任何错误吗？ 
> 
> I also know of a problem that can happen if another extension tries to request too many files in a short period, Chrome will block these "spam" requests and not try to reload them later, so it could block my files from loading if it starts loading around the same time. But that would be visible in the browser console too, so really that's the best starting point to look.我还知道，如果另一个扩展尝试在短时间内请求太多文件，可能会发生一个问题。Chrome会阻止这些“垃圾邮件”请求，而不会尝试稍后重新加载它们，因此，如果在同一时间开始加载，它可能会阻止我的文件加载。但这在浏览器控制台中也是可见的，所以这是最好的起点。我还知道，如果另一个扩展尝试在短时间内请求太多文件，可能会发生一个问题。Chrome会阻止这些“垃圾邮件”请求，而不会尝试稍后重新加载它们，因此，如果在同一时间开始加载，它可能会阻止我的文件加载。但这在浏览器控制台中也是可见的，所以这是最好的起点 我还知道，如果另一个扩展尝试在短时间内请求太多文件，可能会发生一个问题。Chrome会阻止这些“垃圾邮件”请求，而不会尝试稍后重新加载它们，因此，如果在同一时间开始加载，它可能会阻止我的文件加载。但这在浏览器控制台中也是可见的，所以这是最好的起点。

Have you solved the problem? I also have the same problem. When you enter tag, you will not see any response from the plug-in. The web console is reporting an error

**Comment by PuDood** [comment]
2script.js?1674475563.4640124:38 
        
       Cannot read properties of null (reading 'innerHTML') TypeError: Cannot read properties of null (reading 'innerHTML')
    at checkPrompts (dreambooth.js?1678174934.4355032:542:29)
    at dreambooth.js?1678174934.4355032:513:9
    at NodeList.forEach (<anonymous>)
    at dreambooth.js?1678174934.4355032:508:51
    at runCallback (script.js?1674475563.4640124:36:9)
    at script.js?1674475563.4640124:42:31
    at Array.forEach (<anonymous>)
    at executeCallbacks (script.js?1674475563.4640124:42:11)
    at MutationObserver.<anonymous> (script.js?1674475563.4640124:54:9)
runCallback @ script.js?1674475563.4640124:38
pos.baidu.com/dcsm?conwid=240&conhei=350&rdid=6818871&dc=3&di=u6818871&s1=2839721755&dtm=HTML_POST:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
4script.js?1674475563.4640124:38 
        
       Cannot read properties of null (reading 'innerHTML') TypeError: Cannot read properties of null (reading 'innerHTML')
    at checkPrompts (dreambooth.js?1678174934.4355032:542:29)
    at dreambooth.js?1678174934.4355032:513:9
    at NodeList.forEach (<anonymous>)
    at dreambooth.js?1678174934.4355032:508:51
    at runCallback (script.js?1674475563.4640124:36:9)
    at script.js?1674475563.4640124:42:31
    at Array.forEach (<anonymous>)
    at executeCallbacks (script.js?1674475563.4640124:42:11)
    at MutationObserver.<anonymous> (script.js?1674475563.4640124:54:9)
runCallback @ script.js?1674475563.4640124:38
:7860/file=extensions/a1111-sd-webui-tagcomplete-10w/tags/danbooru-index.csv?1678616306979:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
tagAutocomplete.js?1678616179.1791432:94 
        
       Error loading tags file: TypeError: Failed to fetch
loadTags @ tagAutocomplete.js?1678616179.1791432:94
:7860/file=extensions/a1111-sd-webui-tagcomplete-10w/tags/danbooru-10w-zh_cn.csv?1678616311248:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
tagAutocomplete.js?1678616179.1791432:119 
        
       Error loading translations file: TypeError: Failed to fetch
loadTranslations @ tagAutocomplete.js?1678616179.1791432:119
8script.js?1674475563.4640124:38 
        
       Cannot read properties of null (reading 'innerHTML') TypeError: Cannot read properties of null (reading 'innerHTML')
    at checkPrompts (dreambooth.js?1678174934.4355032:542:29)
    at dreambooth.js?1678174934.4355032:513:9
    at NodeList.forEach (<anonymous>)
    at dreambooth.js?1678174934.4355032:508:51
    at runCallback (script.js?1674475563.4640124:36:9)
    at script.js?1674475563.4640124:42:31
    at Array.forEach (<anonymous>)
    at executeCallbacks (script.js?1674475563.4640124:42:11)
    at MutationObserver.<anonymous> (script.js?1674475563.4640124:54:9)
runCallback @ script.js?1674475563.4640124:38
tagAutocomplete.js?1678616179.1791432:421 你好吗,
26script.js?1674475563.4640124:38 
        
       Cannot read properties of null (reading 'innerHTML') TypeError: Cannot read properties of null (reading 'innerHTML')
    at checkPrompts (dreambooth.js?1678174934.4355032:542:29)
    at dreambooth.js?1678174934.4355032:513:9
    at NodeList.forEach (<anonymous>)
    at dreambooth.js?1678174934.4355032:508:51
    at runCallback (script.js?1674475563.4640124:36:9)
    at script.js?1674475563.4640124:42:31
    at Array.forEach (<anonymous>)
    at executeCallbacks (script.js?1674475563.4640124:42:11)
    at MutationObserver.<anonymous> (script.js?1674475563.4640124:54:9)
runCallback @ script.js?1674475563.4640124:38
5prompt-bracket-checker.js?1674475563.4510005:63 
        
       Uncaught TypeError: Cannot read properties of null (reading 'title')
    at checkBrackets (prompt-bracket-checker.js?1674475563.4510005:63:35)
    at HTMLTextAreaElement.<anonymous> (prompt-bracket-checker.js?1674475563.4510005:93:9)
6script.js?1674475563.4640124:38 
        
       Cannot read properties of null (reading 'innerHTML') TypeError: Cannot read properties of null (reading 'innerHTML')
    at checkPrompts (dreambooth.js?1678174934.4355032:542:29)
    at dreambooth.js?1678174934.4355032:513:9
    at NodeList.forEach (<anonymous>)
    at dreambooth.js?1678174934.4355032:508:51
    at runCallback (script.js?1674475563.4640124:36:9)
    at script.js?1674475563.4640124:42:31
    at Array.forEach (<anonymous>)
    at executeCallbacks (script.js?1674475563.4640124:42:11)
    at MutationObserver.<anonymous> (script.js?1674475563.4640124:54:9)
runCallback @ script.js?1674475563.4640124:38
script.js?1674475563.4640124:38 
        
       Cannot read properties of null (reading 'innerHTML') TypeError: Cannot read properties of null (reading 'innerHTML')
    at checkPrompts (dreambooth.js?1678174934.4355032:542:29)
    at dreambooth.js?1678174934.4355032:513:9
    at NodeList.forEach (<anonymous>)
    at dreambooth.js?1678174934.4355032:508:51
    at runCallback (script.js?1674475563.4640124:36:9)
    at script.js?1674475563.4640124:42:31
    at Array.forEach (<anonymous>)
    at executeCallbacks (script.js?1674475563.4640124:42:11)
    at MutationObserver.<anonymous> (script.js?1674475563.4640124:54:9)



> @PuDood
> 
> > The web console is reporting an errorweb控制台报告错误
> 
> What's the error and where does it say it happens? I need a few more details to know what went wrong for you.错误是什么？它在哪里发生？我需要更多的细节来了解你出了什么问题。

I'm sorry to be careless. The above is the error content of the webpage. This is another similar plug-in developed based on your plug-in, but I can be sure that your plug-in will have the same problem with me

https://github.com/inlhx/a1111-sd-webui-tagcomplete-10w

**Comment by PuDood** [comment]
> @PuDood
> 
> > The web console is reporting an errorweb控制台报告错误web控制台报告错误 web控制台报告错误
> 
> What's the error and where does it say it happens? I need a few more details to know what went wrong for you.错误是什么？它在哪里发生？我需要更多的细节来了解你出了什么问题。错误是什么？它在哪里发生？我需要更多的细节来了解你出了什么问题 错误是什么？它在哪里发生？我需要更多的细节来了解你出了什么问题。



> @PuDood
> 
> > The web console is reporting an error
> 
> What's the error and where does it say it happens? I need a few more details to know what went wrong for you.

I'm lucky to use your plug-in, but the problem is that you input tag, and your plug-in doesn't give me any response or display a prompt box. I'm confused. I'm Technical whites

**Comment by DominikDoom** [comment]
There are some unrelated errors as well, but this is the important part:

```
runCallback @ script.js?1674475563.4640124:38
:7860/file=extensions/a1111-sd-webui-tagcomplete-10w/tags/danbooru-index.csv?1678616306979:1

   Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
tagAutocomplete.js?1678616179.1791432:94

   Error loading tags file: TypeError: Failed to fetch
```

Are you using an ad blocker or similar network extensions? net::ERR_BLOCKED_BY_CLIENT usually means the browser or a browser extension blocked the request.

**Comment by PuDood** [comment]
> There are some unrelated errors as well, but this is the important part: ❗ 🔄 
> 
> ```
> runCallback @ script.js?1674475563.4640124:38
> :7860/file=extensions/a1111-sd-webui-tagcomplete-10w/tags/danbooru-index.csv?1678616306979:1
> 
>    Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
> tagAutocomplete.js?1678616179.1791432:94
> 
>    Error loading tags file: TypeError: Failed to fetch
> ```
> 
> 您是否正在使用广告拦截器或类似的网络扩展？net：：ERR_BLOCKED_BY_CLIENT 通常表示浏览器或浏览器扩展程序阻止了请求. ❗ 🔄

<img width="1198" alt="屏幕截图 2023-03-12 190445" src="https://user-images.githubusercontent.com/127589252/224540462-01a4f068-b7cd-45ba-9abd-c82885e714a6.png">
Yes,!!!! but closing is still invalid

**Comment by PuDood** [comment]
> There are some unrelated errors as well, but this is the important part:
> 
> ```
> runCallback @ script.js?1674475563.4640124:38
> :7860/file=extensions/a1111-sd-webui-tagcomplete-10w/tags/danbooru-index.csv?1678616306979:1
> 
>    Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
> tagAutocomplete.js?1678616179.1791432:94
> 
>    Error loading tags file: TypeError: Failed to fetch
> ```
> 
> Are you using an ad blocker or similar network extensions? net::ERR_BLOCKED_BY_CLIENT usually means the browser or a browser extension blocked the request.

I'm testing the browser

**Comment by DominikDoom** [comment]
dreambooth.js is not one of this scripts files, so it is likely from another webui extension. It will probably disappear if you disable those.

Is there still any "failed to fetch" or ERR_BLOCKED_BY_CLIENT in the errors? Or more specifically any error that mentions tagAutocomplete.js as its source.

**Comment by PuDood** [comment]
> dreambooth.js is not one of this scripts files, so it is likely from another webui extension. It will probably disappear if you disable those.
> 
> Is there still any "failed to fetch" or ERR_BLOCKED_BY_CLIENT in the errors? Or more specifically any error that mentions tagAutocomplete.js as its source.

I don't know how to check where these errors are, so I'm not sure. There are still errors when replacing the browser. The new browser has just been installed and how to set it

**Comment by DominikDoom** [comment]
One of the errors at the top says "Intercepted by the IDM Advanced Integration"

It seems you have Internet Download Manager installed and it is blocking those files. Try to disable IDM Advanced Integration.

**Comment by PuDood** [comment]
> One of the errors at the top says "Intercepted by the IDM Advanced Integration"
> 
> It seems you have Internet Download Manager installed and it is blocking those files. Try to disable IDM Advanced Integration.

Thank you very, very much for your help. I can only worship you and your field

**Comment by luojiesi** [comment]
Sorry for the late reply. It fixed itself after a few browser restarts. Not sure what was the original issue though.
