### ISSUE TITLE
Request to join the development team to submit new features

### ISSUE THREAD

**Issue by inlhx** [DominikDoom/a1111-sd-webui-tagcomplete#138]
Request to join the development team to submit new features

https://github.com/inlhx/a1111-sd-webui-tagcomplete-10w

![图新增中文对照翻译](https://raw.githubusercontent.com/inlhx/a1111-sd-webui-tagcomplete-10w/main/img/6.png)

**Comment by DominikDoom** [comment]
Please submit pull requests if you want to add new features, it is easier for me to approve or request changes in that way.

I do not speak Chinese, all translation has been done by community members or using machine translation. So it is not as easy to see your changes for me by just using your link.
