### ISSUE TITLE
更新新版本后，显示空白框。没有字

### ISSUE THREAD

**Issue by bhj8** [DominikDoom/a1111-sd-webui-tagcomplete#140]
更新新版本后，已经反复清除缓存、开启全局代理、重启、还是不行。提示框没有字，就一个白框。
不知道别人有没有这样的问题。

**Comment by DominikDoom** [comment]
(机器翻译)

我需要一些更多的细节来有效地帮助你。在webui终端或浏览器控制台中是否有任何错误？

**Comment by toshiocn** [comment]
> 

控制台中没有错误信息，输入关键词后提示框会出现，也可以选中提示框，但是提示框中没有任何内容（由于提示框中没有任何内容，所以提示框会非常窄）。

**Comment by DominikDoom** [comment]
@toshiocn 
如上所述，只有描述对我来说是不够的，因为我无法在我的系统上重现它。对我来说，无论是否有中文翻译，用正常的标签都能正常工作。也没有视觉错误。

如果在浏览器控制台中真的没有错误，我需要更多关于你的配置的信息，比如webui版本，你使用的浏览器和你对这个扩展的设置。

另外，由于这是另一个中国用户最近遇到的问题，请检查是否有一个浏览器扩展，如广告拦截器或下载管理器阻止了文件请求。

**Comment by DominikDoom** [comment]
@toshiocn 谢谢你的信息，通过比较选项，我发现这是因为 "Only show alias" 的设置。我似乎在过去的一次更新中破坏了这一功能而没有注意到，我将很快修复它。
