### ISSUE TITLE
after update webui, tagcomplete not working

### ISSUE THREAD

**Issue by ZxNozomi** [DominikDoom/a1111-sd-webui-tagcomplete#143]
I usually update webui to a new version, but after updating webui to the latest version of ui update today, tagcomplete doesn't work, can anyone solve this problem?

**Comment by tapdo** [comment]
me too

**Comment by nhocangian** [comment]
yea i left the A111 automatic updating and now i regret it, gotta wait for this to update i guess

**Comment by DominikDoom** [comment]
Sorry for the delay, it should work again now.
You will probably need to restart the webui completely after updating, just the Reload UI / Apply and Restart button wasn't enough for me when I tested it just now.

**Comment by PapaBones** [comment]
Still somewhat broken, I can no longer see what I am selecting with arrow keys and it now takes moves the entire UI which it did not before.

**Comment by ZxNozomi** [comment]
> Sorry for the delay, it should work again now. You will probably need to restart the webui completely after updating, just the Reload UI / Apply and Restart button wasn't enough for me when I tested it just now.
thank you I really appreciate

**Comment by ZxNozomi** [comment]
Thank you, I really appreciate it, it's back to normal

**Comment by DominikDoom** [comment]
@PapaBones The window moving with the text cursor while you type is an intended feature that was added a while ago, you can disable it in the settings. Look for "Move completion popup together with text cursor".
 The arrow key selection looks normal for me though:
![image](https://user-images.githubusercontent.com/34448969/227726339-66a7b575-e502-4b41-8e6f-652acbd897e0.png)
