### ISSUE TITLE
CSS Stylesheet not being applied, resulting in broken UI

### ISSUE THREAD

**Issue by CarbonatedPastries** [DominikDoom/a1111-sd-webui-tagcomplete#146]
Since the Gradio update, the UI has been broken, pushing elements and overlapping most of the page. Checking around the code, it seems like the stylesheet isn't being added to the page, so it just renders raw and breaks the page whenever the UI appears. I don't see errors in the console, so I'm unsure why it isn't applying it.

Tested in Firefox and Chrome.

**Comment by Vigilence** [comment]
I have the same issue. 

![2023-03-26_19-26-16](https://user-images.githubusercontent.com/22781570/227811472-a66a8466-6e4a-4a7b-a419-ddf3c616a9a5.jpg)

**Comment by DominikDoom** [comment]
I don't see this problem on either Chrome or Firefox, both look and work exactly as they should on my system with the newest webui version.
Chrome:
![image](https://user-images.githubusercontent.com/34448969/227811278-140107e8-ae97-48a4-88c0-0530a39cfac9.png)
Firefox:
![image](https://user-images.githubusercontent.com/34448969/227811287-e8a8e7a8-23c6-45de-bbac-1e0cdf67cfa1.png)

Does this style tag not exist for you?
![image](https://user-images.githubusercontent.com/34448969/227811378-058d55db-caf7-4cc4-8d01-c54f927c0b1a.png)

**Comment by FizzieBenK** [comment]
Same issue and as far as i can tell, that style tag doesnt show up for me either.
Using Chrome.
![image](https://user-images.githubusercontent.com/122628783/227812356-41f0c068-eaa5-4db2-a4b2-13132431320f.png)

**Comment by DominikDoom** [comment]
The last part sounds like it might be an issue caused by another extension, since those work for me without issues as well. I'll only be able to take a closer look tomorrow, but in the meantime one thing you could try is disabling extensions one by one to find a possible compatibility issue. Of course that only makes sense if tag autocomplete alone without any other extensions works in the first place, if not then there might be a deeper issue.

**Comment by CarbonatedPastries** [comment]
Your theory was correct: Looks like `openpose-editor` extension is somehow causing this extension to not apply its style element to the page. Not sure what side has more fault - not sure where to look in the code specifically - but it's a start.

**Comment by CarbonatedPastries** [comment]
Turns out it was the `openpose-editor` extension overriding the `gradioApp()` function (fkunn1326/openpose-editor#96), which was [fixed](https://github.com/fkunn1326/openpose-editor/commit/7046777f3b31c607b4a7261777273caf42ab784e) today.

For anyone else affected by issues with other extensions, update your `openpose-editor` extension.
