### ISSUE TITLE
Allow pressing enter to create new line when no option in dropdown is selected

### ISSUE THREAD

**Issue by scrumpyman** [DominikDoom/a1111-sd-webui-tagcomplete#147]
I keep having to click off of the prompt box (often multiple times because the drop down doesn't always disappear) and then quickly click and press enter to create a new line before the drop down appears. No reason enter key should be disabled before an option is selected.

**Comment by DominikDoom** [comment]
Now works like you suggested. As a small side note, you can also just press escape if you want to close the popup at any time, no need to click off and on again.
