### ISSUE TITLE
关于翻译文件的建立办法，

### ISSUE THREAD

**Issue by scj008** [DominikDoom/a1111-sd-webui-tagcomplete#148]
我很喜欢翻译这个功能，输入中文就能使用一些常用的标签，但我发现这个文件在使用的过程中会比较麻烦。
一、首先翻译的文件，条件是需要在主提示词里有这个词，翻译里的内容才能显示。应该是这么应用的吧？
二、我看到有一个旧版的三行内容，我不知道三行的旧版内容的CVS文件的规范写法是如何的，是不是<主提示词>,<翻译词>,<翻译内容>这样的关系？

**Comment by DominikDoom** [comment]
(这是机器翻译的，如果我对你的问题有误解，请原谅)

新的格式只是
<英文标签>,<译文>。

因此,它应该看起来像这样：
1girl,1个女性
solo,单个人物
long_hair,长发
...

旧的格式在标签和翻译之间有一个未使用的0作为占位符，这是因为在翻译系统被重做之前，它原本是别名系统的一部分。如果你做一个新的文件，没有必要使用旧的格式。这只是为了与社区现有的一些旧文件兼容，而不需要对其进行编辑（例如 #23 中的文件）

**Comment by scj008** [comment]
非常开心来自你的回复，我大致了解了这个文件的结构。
通常我会把翻译的文件放在# Translation settings 标签下的文件里，而你给我的#23文件，他是把翻译的文件放置在 # Extra file settings标签下，应该说各有各的好处。


如果我只在 # Translation settings:（）标签里加入【long_hair,长发】
但是# Main tag file（） 标签里如果没有【long_hair,,,】那么搜索将会不可用。

【所以我希望# Translation settings 这个标签里的内容能直接被搜索，而不用在# Main tag file 里面也添加这个词】

但你的# Extra file settings 反而提供了，提示词，数量，翻译的功能，相对来说，反而这个标签文件内容对于翻译来说更加有效。

**Comment by scj008** [comment]
> ，现在，现在明白在问了是对，翻译对，翻译翻译设置只只针对针对存在存在于于文件中的的的标签标签。。。如果如果如果用户用户不知道英文知道知道英文英文是有帮助的，所以它只对已经存在的标签有意义。
> 
> ＃23，，翻译翻译没有的的的的的的的的的的的的用于两两。。从从从，该。从从从从该该系统系统发生了很很大大大的变化（csv列）（csv列）所以它们文件的，不不的用来现有现有的信息。。。另另一一，翻译方面方面另信息
> 
> 它们都的，但/组合组合起来却难说准确地说，它们。，它们。，它们时是，但一体，但一体，但但，但了了，因为被被，如果用户选择的文件太大，有时会完全破坏脚本。

的确我相信你有这么做的目的和作用，也非常感谢你的再次回复。也非常喜欢你建立的这个插件，相对来说这对于新手真的有非常大的帮助。但对于一个中文使用者来说，这可能会有习惯上的有一些不同，我也觉的很奇怪当初为什么会这么设计框架。

好了，我相信我明白了。而我觉得，如果你临时的想要加入一些词，更好的办法是加入到 # Translation settings这个标签，而TRANSLATION SETTINGS标签与MAIN TAG FILE标签，我会用EXECL 里的vookup命令来筛选一次。（因为如果我不小心更改了原始文件，但没有及时的更新翻译文件，那么翻译文件将会有比较多的垃圾数据载入系统，而这些数据之后将会认为是一种BUG。）

非常抱歉这么小的一个问题，这么多次的打扰您。再此非常感谢。我是一个初学者，谢谢你给我的回复，很开心也很满足。再次感谢。另外，我引用了你的文件，新建了一个项目，以便我在GOOGLE COLAB上同步我的翻译 内容使用，希望你不要介意我的行为。谢谢。

**Comment by tvsj** [comment]
包含括号的会被自动添加反斜杆进行转义，这个怎么取消

**Comment by scj008** [comment]
> 包含抽号的会被自动添加反斜杆进入转义，这个怎么取消

好像有二种情况需要会发生你这样的情况，
一种是你加了括号，他就不能翻译出来，
另外一种就是你自己输入的词里带了括号。

你可以尝试下，设置里的  “对插入的括号进行转义”，选项。

**Comment by tvsj** [comment]
> > 包含抽号的会被自动添加反斜杆进入转义，这个怎么取消
> 
> 好像有二种情况需要会发生你这样的情况， 一种是你加了括号，他就不能翻译出来， 另外一种就是你自己输入的词里带了括号。
> 
> 你可以尝试下，设置里的 “对插入的括号进行转义”，选项。

谢谢，上次提问后仔细找了一遍，已经找到了相应的设置项，非常感谢你的回复

**Comment by hsucham** [comment]
期待这个项目下有人可以做一个中文甚至多语言的csv数据集，更进一步让prompt技术民主化:)

**Comment by DominikDoom** [comment]
我将关闭这个问题，因为它主要是在讨论 #164 中解决的，请随时为其他建议打开一个新的问题。
