### ISSUE TITLE
Error executing callback ui_settings_callback

### ISSUE THREAD

**Issue by whitesky1226** [DominikDoom/a1111-sd-webui-tagcomplete#151]
前两天可以正常运行该插件。
今天加载webui时出现以下提示：
Error executing callback ui_settings_callback for E:\AI painting\novelai-webui-aki-v2\extensions\a1111-sd-webui-tagcomplete\scripts\tag_autocomplete_helper.py
Traceback (most recent call last):
  File "E:\AI painting\novelai-webui-aki-v2\modules\script_callbacks.py", line 143, in ui_settings_callback
    c.callback()
  File "E:\AI painting\novelai-webui-aki-v2\extensions\a1111-sd-webui-tagcomplete\scripts\tag_autocomplete_helper.py", line 297, in on_ui_settings
    }""", """Configure Hotkeys. For possible values, see https://www.w3.org/TR/uievents-key, or leave empty / set to 'None' to disable. Must be valid JSON.""", gr.Code, lambda: {"language": "json", "interactive": True}, section=TAC_SECTION))
AttributeError: module 'gradio' has no attribute 'Code'

禁用该插件后一切恢复正常。请问我这边哪里出了问题😂？谢谢！

**Comment by DominikDoom** [comment]
(机器翻译)

这很简单。gradio.Code()只在新版本中可用。你必须更新你的webui，使其获得这些变化，或者使用今天添加这些设置之前的旧版本的tag-autocomplete。
我不能为旧版本添加回退功能，因为当前版本的脚本依赖于这些选项的存在。

**Comment by DominikDoom** [comment]
与我的预期不同，我在尝试了一段时间后，能够添加一个回退，所以如果你还没有更新你的webui，现在应该还能工作。

**Comment by whitesky1226** [comment]
> 与我的预期不同，我在尝试了一段时间后，能够添加一个回退，所以如果你还没有更新你的webui，现在应该还能工作。

OK, thx a lot😊
