### ISSUE TITLE
Not working at all for me after updating

### ISSUE THREAD

**Issue by Ghost4242** [DominikDoom/a1111-sd-webui-tagcomplete#152]
Error I am getting:

```
Error executing callback ui_settings_callback for F:\Stablediffusion\Stablediffusion3\stable-diffusion-webui\extensions\tag-autocomplete\scripts\tag_autocomplete_helper.py
Traceback (most recent call last):
  File "F:\Stablediffusion\Stablediffusion3\stable-diffusion-webui\modules\script_callbacks.py", line 137, in ui_settings_callback
    c.callback()
  File "F:\Stablediffusion\Stablediffusion3\stable-diffusion-webui\extensions\tag-autocomplete\scripts\tag_autocomplete_helper.py", line 297, in on_ui_settings
    }""", """Configure Hotkeys. For possible values, see https://www.w3.org/TR/uievents-key, or leave empty / set to 'None' to disable. Must be valid JSON.""", gr.Code, lambda: {"language": "json", "interactive": True}, section=TAC_SECTION))
AttributeError: module 'gradio' has no attribute 'Code'
```

So what have I messed up? I am using latests Automatic1111 + Torch 2.0.0+ Cu118
This is what the bottom of my webui says
python: 3.10.6  •  torch: 2.0.0+cu118  •  xformers: N/A  •  gradio: 3.16.2  •  commit: [0cc0ee1b]  •  checkpoint: [8c250e7c06]

**Comment by DominikDoom** [comment]
You are not using the latest webui version, since that uses gradio 3.23 while yours is still 3.16.
Your webui commit hash is also not matching latest.

Either update your webui or don't use the latest version of tag autocomplete until you do for now.
I'll try to add a fallback later since apparently more people than I thought are still using the older version currently.

**Comment by Ghost4242** [comment]
> You are not using the latest webui version, since that uses gradio 3.23 while yours is still 3.16. Your webui commit hash is also not matching latest.
> 
> Either update your webui or don't use the latest version of tag autocomplete until you do for now. I'll try to add a fallback later since apparently more people than I thought are still using the older version currently.

Sorry I saw now that I didn't use the latest but I updated now so it works

**Comment by 6thfieldarmy** [comment]
hey man, I just updated the webui to gradio 3.23.0 but it still doesn't work, it's already up to date
