### ISSUE TITLE
Broken autofill since A111 gradio update

### ISSUE THREAD

**Issue by Evil-Dragon** [DominikDoom/a1111-sd-webui-tagcomplete#153]
It still works technically but my autofill now looks like this:
<img width="190" alt="firefox_daFrvBwFpH" src="https://user-images.githubusercontent.com/9480613/229651381-d981dbde-d899-4a37-b124-96e9cb617aa4.png">

Tried disabling cache with F12 to force any potential new css but it's still the same.

**Comment by zisonMyu** [comment]
this is a problem in a111v2.2, v2.1 wont launch at all……

**Comment by DominikDoom** [comment]
That looks like the issue in #146.
The culprit the was a broken outdated version of the openpose editor extension, are you perhaps using that too?

**Comment by Evil-Dragon** [comment]
Yep, just found that out. Sorry, I had no idea that was causing the issue.
