### ISSUE TITLE
module 'gradio' has no attribute 'Code'

### ISSUE THREAD

**Issue by bxjxxyy** [DominikDoom/a1111-sd-webui-tagcomplete#155]
虚拟环境已经pip install gradio安装成功了，webui其他功能正常。只有tagcomplete报错。

**Comment by DominikDoom** [comment]
请阅读 #151。这是一个版本问题，请更新你的webui。尽管如果你使用最新的标签自动完成版本，它应该已经被今天的更新所修复。
