### ISSUE TITLE
Does not show up anymore

### ISSUE THREAD

**Issue by hexahigh** [DominikDoom/a1111-sd-webui-tagcomplete#157]
I recently updated python version and updated the webui. I dont know what could have caused this but after doing this the autocomplete popup no longer shows up. I get alot of error in the javascript console on my browser when typing something in but this could be completely unrelated. I tried reinstalling the extension but it still doesnt work.

**Comment by DominikDoom** [comment]
Well, what are the errors? Even if they are unrelated, they might still be a good starting point.
But it's likely they are, since you said they appear while typing. The script listens to textbox changes and executes on every key press, so it would fit your description.

**Comment by hexahigh** [comment]
Weirdly enough the errors stopped appearing after making this issue. It still doesnt work but im only getting one error.

[console-export-2023-4-9_18-56-14.txt](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/files/11185923/console-export-2023-4-9_18-56-14.txt)

**Comment by hexahigh** [comment]
The error comes from the extension

**Comment by hexahigh** [comment]
Here is my launch command if that could be what causes the issue: 
<pre>
py -3.10 launch.py --share --disable-safe-unpickle --no-half-vae --xformers --reinstall-xformers --reinstall-torch --enable-insecure-extension- --gradio-queue --remotemoe
pause
<pre<

**Comment by DominikDoom** [comment]
Is the extension up to date? It says in the error that modelDropdown is null, which was an issue after the webui updated to a newer Gradio version and some UI elements changed the way they function. But that should already be fixed in recent versions of tag-autocomplete, so the issue might be if you updated one but not the other.

**Comment by hexahigh** [comment]
In the webui it says its up to date but i will try manually deleting the extension and reinstalling

**Comment by hexahigh** [comment]
That was the issue. The webui said it was up-to-date but it was over 300 changes behind.

**Comment by hexahigh** [comment]
Thanks alot for the help

**Comment by DominikDoom** [comment]
Glad I could help you!
Although the up-to-date display in the webui should be correct. It directly compares the git head states to see if you're behind, so unless you switched to an older branch manually at some point it should be accurate. It could also just be another issue with loading or the cache that resolved itself after a clean reinstall though.
