### ISSUE TITLE
extention stopped working after recent update

### ISSUE THREAD

**Issue by Jegantha** [DominikDoom/a1111-sd-webui-tagcomplete#158]
Greetings,

Earlier this week I updated automatic1111 for the first time in about two months, and it seems that this extention stopped working. I removed the extention and added it again, but this didn't solve the issue. I've checked the settings and csv files, and those all seem fine. 

Does anyone else have similar problems and/or know how to fix this? Thanks.

**Comment by DominikDoom** [comment]
This seems to be a common problem after the big Gradio update the webui recently did, but the current version of tag autocomplete already has the necessary fixes. Similarly to #152 and #157, please make sure you use the most recent version of tag autocomplete and make sure to completely restart the webui after updating/reinstalling, the "Restart UI" button isn't enough in some cases. Also try CTRL+F5 to force a cache refresh.

If this doesn't work, or you've already tried it, the next step would be to look if any javascript errors show up in your browsers console.

**Comment by Jegantha** [comment]
Hi, thanks for the quick reply. 

I never actually saw any errors. It's just that nothing happens anymore when I start typing in my prompt.

I'm not sure how to force it to download the correct version. It shows my current version of the extension as 223abf54 (Wed Apr 5 11:05:44 2023), and neither "check for updates" nor "apply and restart" change that. I manually downloaded the latest version 2.1.0 and replaced the javascript, scripts and tags folders. Afterwards I started A1111 again, but to no avail.

**Comment by DominikDoom** [comment]
Are you using any other extensions? If so please try deactivating everything other than this one, just to make sure it's not a compatibility problem. Trying on another browser might be a good check to do as well.

**Comment by Renari** [comment]
I ran into this as well:
```
2023-04-12 17:17:45.402300+00:00ValueError: File cannot be fetched: /stable-diffusion-webui/extensions/a1111-sd-webui-tagcomplete/javascript/ext_loras.js. All files must contained within the Gradio python app working directory, or be a temp file created by the Gradio python app.
```
Is dumped out in my log for every file from the extension.

**Comment by Jegantha** [comment]
![2023-04-13 22_14_59-Greenshot](https://user-images.githubusercontent.com/130408659/231873422-739414ed-9173-4082-bdfb-2cd6cbea51a8.png)
![2023-04-13 22_15_50-Greenshot](https://user-images.githubusercontent.com/130408659/231873430-2e1406e2-67d0-4b0f-ae37-b164530c35c6.png)

All this time I thought ppl were talking about getting errors in the command window of a1111. Turns out I was indeed getting a lot of errors in the console of the browser. Mybad!

The first image has the errors I get upon starting. Whenever I start typing in the prompt window I get several errors like the one in the second image. Does this mean that there is a different solution? I typed the lines you suggested into the console but it's telling me that tagBasePath and CFG are undefined.

**Comment by DominikDoom** [comment]
Yeah it seems the script isn't loaded correctly.
In the first error it says "redeclaration", do you maybe have a duplicate version of the extension that is somehow interfering? The rest of the errors most likely come from these global variables missing as well. Also make sure that you don't have the old legacy version of the script installed (before extensions were a thing), where the files would be dropped off in the webui's root Javascript and scripts folders instead of the extensions subdirectory. Or maybe you put them there recently by mistake?

**Comment by Jegantha** [comment]
There was indeed an old version (25/10/22) in the main javascript folder. After removing that file everything works again. Thank you very much! :)
