### ISSUE TITLE
proposal: prompt analyze and user tag set auto generate?

### ISSUE THREAD

**Issue by ssddi456** [DominikDoom/a1111-sd-webui-tagcomplete#165]
may we record each process's prompt, extract tags, and generate a user tag set automatically?
or could accept an external tag file in config?

**Comment by DominikDoom** [comment]
Doing this automatically is a bit much, but you can easily add your own custom tags by creating a new .csv file in the extension's `tags` folder and following the format described in the README for either full tag sets or extra tags. I'd recommend extra tags, they are meant precisely for small sets of custom tags like this that exist outside the normal tag ordering.

If you just mean it as a "favorites" list of sorts, I think it would be easier to instead use the webuis built-in Styles feature to save small or large parts, or even full prompts, for stuff that you regularly use or found works well with certain models. You can also use `{prompt}` there to specify where it should be inserted, for example saving `masterpiece, best quality, {prompt}` as a style will always put those modifiers before the rest and before other styles.

**Comment by DominikDoom** [comment]
Closing this as stale and out of scope, feel free to reopen if my suggestions didn't fit your needs.
