### ISSUE TITLE
UI is broken

### ISSUE THREAD

**Issue by CloclWorld109** [DominikDoom/a1111-sd-webui-tagcomplete#166]
commit: [22bcc7be]
I updated extension and now my UI is not the same as before
![UI](https://user-images.githubusercontent.com/132168564/235323464-e323557d-2a75-4f52-a6c4-6ba9c64b0d10.png)

**Comment by DominikDoom** [comment]
See #146.

TL;DR:
1. Make sure your webui itself is also updated
2. Update your other extensions, especially openpose-editor since older versions broke other extensions.
