### ISSUE TITLE
`Uncaught (in promise) TypeError: Cannot read properties of null (reading 'querySelectorAll')`

### ISSUE THREAD

**Issue by devioa** [DominikDoom/a1111-sd-webui-tagcomplete#173]
我最近把WebUI和这个插件`git pull`更新了后发现插件未工作且控制台有此错误：
![1](https://user-images.githubusercontent.com/38558065/236615298-d93db26b-ad4b-43b8-a5db-c5e7ac2403db.png)

**Comment by DominikDoom** [comment]
现在应该修好了，很抱歉给大家带来不便。如果事后仍有不妥之处，请告诉我。

**Comment by devioa** [comment]
> 现在应该修好了，很抱歉给大家带来不便。如果事后仍有不妥之处，请告诉我。

贵安，感谢
