### ISSUE TITLE
If the webUI was loaded with a blacklisted (or not whitelisted) model, autocompletion popup is shown

### ISSUE THREAD

**Issue by Kiyos** [DominikDoom/a1111-sd-webui-tagcomplete#174]
After some further testing of the #172 fix I found another issue. The summary is in the title. No errors or warnings this time, unfortunately.

![popup_on_a_wrong_model](https://user-images.githubusercontent.com/5103155/236636167-0554b393-bfae-4864-bd5f-0c9429d08868.png)

webUI: 1.1.1 ([5ab7f21](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/5ab7f213bec2f816f9c5644becb32eb72c8ffb89))
Gradio: 3.28.1 (installed automatically)
a1111-sd-webui-tagcomplete: f9f7732
Browser: Chrome 108

To reproduce:
1. In the currently running webUI, activate a model which is definitely in the blacklist (or definitely not in the whitelist) by hash or by name, doesn’t matter.
2. Type 1 in the prompt. The autocompletion popup would not show up. This is expected.
3. Close the browser, shut down the webUI completely.
4. Start the webUI again, wait for it to automatically load the model chosen in the first step. This is expected.
5. Open the browser, type 1 in the prompt. The autocompletion popup will show up, even though it shouldn’t.

**Comment by DominikDoom** [comment]
Good catch, it only updated the hash but not the model name after startup.
And for safety reasons it would skip the black/whitelist checks if either hash or name were empty, to not disable the script by mistake, which is why it defaulted to on in your case.
