### ISSUE TITLE
does not work with gradio 3.28

### ISSUE THREAD

**Issue by blacksino** [DominikDoom/a1111-sd-webui-tagcomplete#175]
Hello,auto complete does not popup with gradio3.28

**Comment by cerseinusantara** [comment]
also not working on 3.16 currently

**Comment by DominikDoom** [comment]
It's working fine for me in 3.28. Please open your browser console (CTRL+SHIFT+I) and tell me if any errors related to tag autocomplete show up, or any errors in the webui terminal window.

**Comment by phoenix** [comment]
Uncaught (in promise) DOMException: Failed to execute 'appendChild' on 'Node': Only one element on document allowed.
    at setup

    gradioApp().appendChild(acStyle);

auto complete can popup,but can not navigate with keyboard

**Comment by phoenix** [comment]
> It's working fine for me on 3.28. Please open your browser console (CTRL+SHIFT+I) and tell me if any errors related to tag autocomplete show up, or any errors in the webui terminal window.

Uncaught (in promise) DOMException: Failed to execute 'appendChild' on 'Node': Only one element on document allowed.
at setup

gradioApp().appendChild(acStyle);

auto complete can popup,but can not navigate with keyboard

**Comment by DominikDoom** [comment]
Does this also happen if other extensions beside tag autocomplete are disabled? This was a problem before with an outdated version of openpose-editor interfering.

**Comment by phoenix** [comment]
> Does this also happen if other extensions beside tag autocomplete are disabled? This was a problem before with an outdated version of openpose-editor interfering.

Thanks,everything works fine after update openpose-editor.

**Comment by roseyyy2022ai** [comment]
Same thing here... not sure which gradio version I have but I believe latest (i'm kind of a noob, sorry)
My error:
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'textContent')
    at updateModelName (_utils.js?1683480837.326589:110:42)
    at setup (tagAutocomplete.js?1683480837.3275893:863:5)
lmk when there's a fix :)
btw i'm using [This Colab notebook](https://colab.research.google.com/drive/1i2wQDB9XAdG_fHXhmr1j7ipr9-Y7-T2S?hl=en#scrollTo=sBbcB4vwj_jm) you can contribute to directly if you find errors in my code as well...

**Comment by DominikDoom** [comment]
@cerseinusantara @roseyyy2022ai I have found the issue for gradio 3.16 (which was a small oversight), should be fixed for you now.

As for @blacksino, 3.28 should work out of the box if you use a recent tag-autocomplete version. So if the issue still exists for you, again, I will need the error message to find out more.

**Comment by blacksino** [comment]
sorry for replying late, caught SyntaxError: Identifier 'loading' has already been declared (at tagAutocomplete.js?1683546999.8080368:1:1):

**Comment by DominikDoom** [comment]
That is very likely an issue with another extension using a variable with the same name. I can probably fix it just by adding a more unique prefix, but just out of interest can you tell me what other extensions you use? Might be good to know in the future if it comes up again.

**Comment by DominikDoom** [comment]
@blacksino Should be fixed now, I added a prefix to make the name more distinct. On another note, I just remembered a similar case with #158. In that case the root issue was a duplicate old version of the autocomplete script in the webui root's javascript folder. So if it still happens to you after the fix, it might be that.
