### ISSUE TITLE
Color setting for wildcard suggestions

### ISSUE THREAD

**Issue by diedpigs** [DominikDoom/a1111-sd-webui-tagcomplete#178]
Hi,

Is there a way to set up color for wildcard suggestions? I am using dark mode, and the pop up list is really hard to read.

![image](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/assets/1854361/945c3cb5-e121-40c1-952a-3cb7642c481d)

Thanks,

**Comment by DominikDoom** [comment]
The wildcards should follow the color scheme just like the rest of the popups. They're not handled differently when it comes to background color, only the text color changes depending on the tag type.
They appear completely normal for me in dark mode:
![image](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/assets/34448969/2631f1a1-fd99-4d00-8603-160ea251fd26) ![image](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/assets/34448969/7b2a3820-6940-4d5a-a675-67f14b50e3a5)

If only wildcards are affected for you, that would be really weird. Are normal tags and the embed/lora suggestions with `<` fine?

Additionaly, please give me the following info:
- What commit of the webui are you on, and which gradio version? (Both visible at the bottom of the page)
- Are there any errors in your browser console (CTRL+SHIFT+I)?
- Which browser are you using?
- Does the problem also occur when other third party extensions except tag autocomplete are disabled?

**Comment by diedpigs** [comment]
- Commit hash: 5ab7f213bec2f816f9c5644becb32eb72c8ffb89
- There are 403 on `api-logo.svg` and `favicon.ico`
- Google Chrome
- Don't have many extensions installed, so I am not sure.


So I ran the webui without `--theme dark` and the webui was in dark color I guess because my browser is set to dark theme, but somehow the tag completion doesn't think it's in dark mode.

After I set `--theme dark` and reload the UI, the tag completion is now showing in dark theme as expected.

**Comment by diedpigs** [comment]
Hi,

Sorry for the late reply.
Yes, my system is also set to dark theme.

I've removed the `--theme dark` and it works just fine. I don't think any of the arguments I use will affect the UI.

Here's my `webui-user.bat`:
```
@echo off

set PYTHON=
set GIT=
set VENV_DIR=
set COMMANDLINE_ARGS=--xformers --lowvram --listen --enable-insecure-extension-access --no-half-vae
set PYTORCH_CUDA_ALLOC_CONF=garbage_collection_threshold:0.6,max_split_size_mb:128
git pull
call webui.bat
```

**Comment by zixzaxlad** [comment]
I have the exact same problem. I'm currently using the kitchen theme, "--theme dark" or not, doesn't affect this kind of behavior. Everything seems fine except for wildcards. Only if I change the kitchen theme to light can the wildcard display with a white background and black text color.

- commit hash:4129eefdcee32d1fadbaf5d59b54dbcb5ee21864(my own branch but it shouldn't matter I've only changed some other minor stuff)
- console error: `Channel: Error in handleResponse UNK/SW_UNREACHABLE contextMenu createContextMenu
_handleResponsePromise @ commons.js:2
(匿名) @ commons.js:2
Promise.catch(异步)
_sendMessageToExtension @ commons.js:2
sendToExtension @ commons.js:2
send @ commons.js:2
listener @ commons.js:2
commons.js:2  Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
fromGeneric @ commons.js:2
fromAny @ commons.js:2
_handleResponsePromise @ commons.js:2
(匿名) @ commons.js:2
Promise.catch(异步)
_sendMessageToExtension @ commons.js:2
sendToExtension @ commons.js:2
send @ commons.js:2
listener @ commons.js:2
`
- Edge

**Comment by DominikDoom** [comment]
@zixzaxlad Sorry, I still have no idea what causes this.
The console error is definitely unrelated though, tag autocomplete has no commons.js file.

As mentioned above, the wildcards don't use separate styling, the only difference to normal tags is that wildcards have no category colors. But the background color is always the same for all tag types, so it is a big mystery to me why only wildcards are affected. Are the Lora etc. completions shown on `<` all unaffected too?
I tried with kitchen theme, that all works fine for me too on Chrome, Edge and Firefox.

I still suspect that some other extension is interfering, so if you have the time, I would suggest trying to turn all others off and see if the problem still happens.

**Comment by Brightmoon-prime** [comment]
If you downloaded the extension a long time ago, you may need to fully delete the extension and redownload it. I had this issue until i deleted the "Tag-Autocomplete" folder in my extensions folder, then i redownloaded it. 
Note: Older versions don't seem to update properly

**Comment by DominikDoom** [comment]
@Brightmoon-prime that is a good point, another issue might be if outside the extensions folder, an old version exists in the webui's root script / javascript folders.

Although, old versions should still update normally if they were installed through git originally. As far as I know the webui's update method completely resets to the current main branch state, which will also delete local modifications or old files not used anymore. But as you said, reinstalling is a safe bet.

**Comment by zixzaxlad** [comment]
@DominikDoom delete and cloned a brand-new version solved the problem. There's no demo chants file in the old tag folder. I don't know if that's the problem.

**Comment by DominikDoom** [comment]
@zixzaxlad Good to hear. I don't think the chants file has any influence on the theme colors, it's more likely that something else in the old version was interfering if it really was only partially updated or something like that.

I'll close this as resolved then, @diedpigs please feel free to reopen if your case isn't solved by a fresh re-clone.
