### ISSUE TITLE
Support for hires fix prompts

### ISSUE THREAD

**Issue by catboxanon** [DominikDoom/a1111-sd-webui-tagcomplete#179]
Only in dev branch currently, but going ahead and opening the issue to track now: https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/ff0e17174f8d93a71fdd5a4a80a4629bbf97f822#diff-e20573334d898aca3a51188e89e2fee20a9273a1139fabe3ec8ca762969f2293R508-R511

**Edit:** Just a heads up all prompts now use the `.prompt` class (normal prompts and hires fix prompts) in the dev branch too. https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/3605407033fa50408239924e77ccf38dcd5225b9

**Comment by DominikDoom** [comment]
Thanks for letting me know. Them all having the `.prompt` class makes it really trivial to support, though I will probably have to leave in the old ID selectors for those using older versions even after dev is merged in.
