### ISSUE TITLE
config.json dosen't work?

### ISSUE THREAD

**Issue by mkco5162** [DominikDoom/a1111-sd-webui-tagcomplete#18]
I added the script on sd-webui and it work.
But I changed "tagFile" to customtags.csv and "maxResults" to 8 but there is no my custom tags csv and maxresults still is 5

**Comment by DominikDoom** [comment]
Very likely a cache issue, hit `CTRL+F5` to force the browser to reload.

**Comment by mkco5162** [comment]
> Very likely a cache issue, hit `CTRL+F5` to force the browser to reload.

oh it work thanks
