### ISSUE TITLE
The prompt word will appear below the input box instead of floating in the input box

### ISSUE THREAD

**Issue by ureytom** [DominikDoom/a1111-sd-webui-tagcomplete#181]
When I use the automatic completion plugin in Edge browser, the prompt word will appear below the input box instead of floating in the input box.
By checking the browser and debugging, it was found that the corresponding style is missing. The error comes from the setup function in the tagAutocomplete. js file (line 1086).
`gradioApp().appendChild(acStyle)`
![image](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/assets/42398154/a3746807-77c8-422f-890f-8b00d60fbc0d)
![image](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/assets/42398154/01f472f4-f7a4-4b05-8dbf-0a02d803a931)

**Comment by ureytom** [comment]
I have solved this problem and the above modifications are as follows
`gradioApp().querySelector('head').appendChild(acStyle)`

**Comment by DominikDoom** [comment]
Update your openpose-editor extension.
#146 #153 #166 #175 #180
