### ISSUE TITLE
[Feature Request] Middle of prompt autocompletes result in double-spacing

### ISSUE THREAD

**Issue by abint** [DominikDoom/a1111-sd-webui-tagcomplete#196]
**Description:**
Immediately following space characters after an autocomplete should be removed to prevent double spacing.

**How it currently works:**
Starting prompt is:

- short hair, green eyes, 1girl

Type from pipe to autocomplete:

- short hair,| green eyes, 1girl

Resulting prompt:

- short hair, cowboy shot, ᠎ green eyes, 1girl

**Desired result:**

- short hair, cowboy shot, green eyes, 1girl

(I added a 0 width to the "resulting prompt" since github strips double spacing)

**Comment by DominikDoom** [comment]
This is a bit of a "conflict of interest" situation.
The current way that will insert its own spaces by default is mainly optimized for typing multiple things in a row. If you type more than one thing in the middle of a prompt and no additional space is added, the cursor would either end up at the beginning of the next tag or with no space after the comma.
So currently it's "delete one space when you're done" vs. "type space after each tag manually".

But I guess I could make it a separate option to enable/disable this behavior if you only add one tag at a time in the middle.
