### ISSUE TITLE
Couldn't launch python  exit code: 3

### ISSUE THREAD

**Issue by karmaacska** [DominikDoom/a1111-sd-webui-tagcomplete#198]
Issue with launching webui-user.bat

Couldn't launch python

exit code: 3

Thanks for the help!

**Comment by DominikDoom** [comment]
This does not seem related to tag autocomplete.
You probably have a permission or path issue with your python installation, see https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/8758 for some suggestions.
