### ISSUE TITLE
AttributeError: 'OptionInfo' object has no attribute 'needs_restart'

### ISSUE THREAD

**Issue by etherealxx** [DominikDoom/a1111-sd-webui-tagcomplete#199]
Thanks DominikDoom & contributors for making this incredibly useful extension✨
.
However i encountered something today
```
Error executing callback ui_settings_callback for /content/volatile-concentration-localux/extensions/a1111-sd-webui-tagcomplete/scripts/tag_autocomplete_helper.py
Traceback (most recent call last):
  File "/content/volatile-concentration-localux/modules/script_callbacks.py", line 143, in ui_settings_callback
    c.callback()
  File "/content/volatile-concentration-localux/extensions/a1111-sd-webui-tagcomplete/scripts/tag_autocomplete_helper.py", line 301, in on_ui_settings
    "tac_activeIn.txt2img": shared.OptionInfo(True, "Active in txt2img").needs_restart(),
AttributeError: 'OptionInfo' object has no attribute 'needs_restart'
```

The stable diffusion version used is camenduru's v2.2 fork
```
git clone -b v2.2 https://github.com/camenduru/stable-diffusion-webui /content/volatile-concentration-localux
```

And specifically i'm using this colab: https://colab.research.google.com/github/etherealxx/volatile-concentration-localux-colab/blob/main/volatile_concentration_localux_colab.ipynb

I am pretty sure your extension still works yesterday or two days ago.

**Comment by etherealxx** [comment]
It's this commit that breaks it i believe: https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/commit/922414b4ba46e31bb8244eea83ee411585f8b840

Maybe consider some backward compatibility?👀

**Comment by basedholychad** [comment]
i'm just encounter the same problem, and start to create new issue, yeah,

**Comment by DominikDoom** [comment]
These methods are part of the webui's 1.3.0 update, which has been out for around two months now - so if you are still on an older version, the easiest solution is to just update.

For now, I was also able to include some very hacky fix by adding an imitation of the missing methods myself if they don't exist, but this creates technical baggage and I will very likely remove it some time in the future for a cleaner codebase.
Especially for forks, I hope that you understand that I will not be able to provide backwards compatibility forever.

**Comment by etherealxx** [comment]
Thank you so much, really appreciated🙏. Forks are also slowly being deprecated/unsupported if it's too old and newer forks became stable enough. It's just that the oldest, still used fork (`camenduru's v2.2`) aren't compatible with your newest commit (before you updated it just now).

Don't worry though, if you're planning to remove the backward compatibility later, we'll just use your old commit (git checkout), but i'm pretty sure the oldest fork will be deprecated soon.
