### ISSUE TITLE
自动补全没有被触发 控制台报错TypeError: Cannot read properties of null (reading 'querySelector')

### ISSUE THREAD

**Issue by Zha-Miku** [DominikDoom/a1111-sd-webui-tagcomplete#210]
SD版本：
![image](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/assets/54501325/bfab07c3-36cf-4c29-9cbc-473d24661517)

插件版本：
![image](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/assets/54501325/a260db34-f597-44f1-a977-9c7118413f05)
设置信息：
![image](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/assets/54501325/d9d77b09-2ec1-4924-a68f-945d37466dde)
和上次的报错不一样，修改了几次这里的设置还是下面的报错
报错信息：
![image](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/assets/54501325/4bc2922e-845f-4f8b-b588-b3bea97ce3fe)

**Comment by DominikDoom** [comment]
querySelector 在该位置为空意味着它没有找到添加到提示文本框的 HTML 容器（可能是因为初始化过程中出了问题，也可能是因为文本框本身没有被正确找到）。

但非常奇怪的是，既然键入监听器使用相同的标识符附加到文本框，那么自动完成功能首先就会触发。
在正常的 txt2img 提示文本框中会出现这种情况吗？

如果禁用了其他扩展，是否也会出现这种情况？特别是自定义主题可能会对其产生影响。
如果没有区别，也要确保其他活动扩展也是最新的。
