### ISSUE TITLE
4a415f1a 译文检索失效

### ISSUE THREAD

**Issue by hadwinfu** [DominikDoom/a1111-sd-webui-tagcomplete#212]
译文能正确出现在补全提示框中，但是直接输入中文无法弹出补全提示框

**Comment by DominikDoom** [comment]
对我来说，它可以正常工作（至少使用微软拼音输入法)。

https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/assets/34448969/4a3f9f67-d9be-4d79-8e87-eae3fd876ae0

最简单的原因就是该设置被关闭了：
![image](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/assets/34448969/eeaae7fb-3970-4e5b-9b1e-48023e67ac95)
如果您使用的是本地化扩展，可能会有不同的叫法，比如 "使用译名搜索"。

**Comment by DominikDoom** [comment]
由于很久没有收到您的回复，我将关闭此问题。如果问题仍然存在，您可以重新打开，并提供更多信息。
