### ISSUE TITLE
csv fail parse

### ISSUE THREAD

**Issue by bluelovers** [DominikDoom/a1111-sd-webui-tagcomplete#214]
model_keyword_support.py
known_lora_hashes.txt

```
"[prosthetic quadruped,Quadruped machinery,mechanical tail,mechanical parts, robot joints,hydraulic system,headgear,four feet].safetensors",85862f62,1684523642.4008722
"Asian Villa, forest background.safetensors",fdea1028,1684355821.3939998
"PrisonClothesOfMerkuriaV1[prison clothes,metal collar,off-shoulder][striped headwear].safetensors",d276b364,1687874248.9270608
```

**Comment by bluelovers** [comment]
https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/issues/206

**Comment by DominikDoom** [comment]
I can still merge it for consistency with the read function, but what is this fix supposed to accomplish in this case? On my system, the results are 100% identical for the example filenames you provided.
Commas were already handled as described in the linked issue by always quoting the file name.
