### ISSUE TITLE
在不 reload ui 的情況下重新讀取 csv 翻譯

### ISSUE THREAD

**Issue by bluelovers** [DominikDoom/a1111-sd-webui-tagcomplete#216]
更改錯誤的 csv 翻譯之後 似乎只能重新讀取 ui 才能更新

![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/167966/0500d8bb-78d4-4854-a267-2fcf86fc0a79)

[danbooru-tags-zh-TW.csv](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/files/12272173/danbooru-tags-zh-TW.csv)

**Comment by DominikDoom** [comment]
这种假设是错误的，当您应用新设置或在快速设置栏中进行更改时，翻译会立即重新加载。
我刚才用你的文件进行了确认，无论之前选择的是什么文件，它都能正常工作。

https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/assets/34448969/7594e262-1419-4d1a-8ced-f329aeca513f

唯一的特殊情况是，如果文件名与之前的相同，通常会跳过热重载，因为它假定没有任何变化。在这种情况下，你必须通过重新加载用户界面或使用此设置按钮来强制刷新：

![image](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/assets/34448969/076d5182-327e-4dd7-ab14-aa35dc5bde6c)

**Comment by bluelovers** [comment]
> 唯一的特殊情况是，如果文件名与之前的相同，通常会跳过热重载，因为它假定没有任何变化。在这种情况下，你必须通过重新加载用户界面或使用此设置按钮来强制刷新：
> 
> ![image](https://user-images.githubusercontent.com/34448969/258733530-076d5182-327e-4dd7-ab14-aa35dc5bde6c.png)

hmm 這個功能 藏的有點遠...
