### ISSUE TITLE
Hope to open the discussion module, so that we can share the translation of Tag

### ISSUE THREAD

**Issue by HalfMAI** [DominikDoom/a1111-sd-webui-tagcomplete#22]
Hope to open the discussion module, so that we can share the translation of Tag

Using google translate and 5k+ line from https://ngabbs.com/read.php?tid=33869519
[danbooru-0-zh-ver1.csv](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/files/9818557/danbooru-0-zh-ver1.csv)

**Comment by DominikDoom** [comment]
@HalfMAI I've enabled Discussions if you want to share it there. We could also put a link to a separate Repo in the README or you could start a PR to add it to the main repo.

**Comment by HalfMAI** [comment]
> @HalfMAI I've enabled Discussions if you want to share it there. We could also put a link to a separate Repo in the README or you could start a PR to add it to the main repo.

Thanks~.  The main consideration since we are all using this plugin, there is a unified discussion place to easily share. If using repo and then pull request words may be very troublesome for you, especially in the case of frequent updates. Or some WIP staff.
Another aspect is that you can not only translate the tag, but also provide a unified place to share the tag.csv.

**Comment by HalfMAI** [comment]
> https://github.com/sgmklp/tag-for-autocompletion-with-translation 你可以看看这个仓库，这是我当时开发翻译支持时使用的文件，如果你找到了不错的Tag翻译，可以向它提交PR。 You can take a look at this repositories. This is the file I used to develop translation support at that time. If you find a good tag translation, you can submit a PR to it

谢谢您，其实我当时看了一下考虑放在您的repo进行pr，但是考虑到如果有更多的例子在同一个库里统一分享，会更方便大家更多的参与其实类型的CSV的分享，所以最后考虑是放在这个库里的 讨论里比较好

**Comment by sgmklp** [comment]
好的，我也期待着通过讨论和分享获得更加实用的Tag文件
