### ISSUE TITLE
This plug-in cannot pop-up prompt words in sd1.5.2

### ISSUE THREAD

**Issue by wangnimaaa** [DominikDoom/a1111-sd-webui-tagcomplete#227]
![Snipaste_2023-08-29_09-53-56](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/assets/129063909/79765b77-95f9-4f5f-9c87-a428b51c1526)
Help me plz

**Comment by DominikDoom** [comment]
I will need more info, everything related to tag autocomplete seems fine in your screenshot.
Open the browser console (CTRL-SHIFT-I) and tell me if there are any errors.

**Comment by wangnimaaa** [comment]
Is that what it looks like? It looks like a lot of mistakes, but I can't understand them
![Snipaste_2023-08-29_19-03-13](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/assets/129063909/83178410-f303-4e45-af5b-db6268d6ce37)

**Comment by wangnimaaa** [comment]
> 是这样的吗？看起来错误很多，但是看不懂 ![Snipaste_2023-08-29_19-03-13](https://user-images.githubusercontent.com/129063909/263998630-83178410-f303-4e45-af5b-db6268d6ce37.jpg)

This pops up every time I click on a link
![Snipaste_2023-08-29_19-04-46](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/assets/129063909/afd86436-340c-415e-9998-7245330c2d60)

**Comment by DominikDoom** [comment]
Yes, that was what I was looking for.
ERR_BLOCKED_BY_CLIENT usually means that the browser or a browser extension (adblocker, firewall, etc.) has prevented the request.
Are you using the ["Internet Download Manager"](https://www.internetdownloadmanager.com/) software? I think that's what the last window is from. Another user previously had an issue where its "Advanced browser integration" feature was blocking the file loads (see the last few comments in #135).

**Comment by wangnimaaa** [comment]
> 是的，这就是我一直在寻找的。 ERR_BLOCKED_BY_CLIENT 通常表示浏览器或浏览器扩展（广告拦截器、防火墙等）已阻止该请求。 您是否使用[“Internet 下载管理器”](https://www.internetdownloadmanager.com/)软件？我想这就是最后一个窗口的来源。[另一个用户之前遇到过一个问题，其“高级浏览器集成”功能阻止了文件加载（请参阅#135](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/issues/135)中的最后几条评论）。

Thank you very much, I disable the idm browser plug-in can be!
![Snipaste_2023-08-29_19-37-58](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/assets/129063909/a2447556-6e37-4c94-b350-0e1df19452df)

**Comment by DominikDoom** [comment]
Glad to see that that was it.
Unrelated question, what are you using as your translation settings? The content of the square brackets [] should normally not be the post count like it is in your case.

**Comment by wangnimaaa** [comment]
this
![Snipaste_2023-08-29_19-48-35](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/assets/129063909/596f7326-6b6f-474c-9490-e4d648dec464)

**Comment by DominikDoom** [comment]
![image](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/assets/34448969/2f1b8342-c553-42b3-8992-be389436344a)
You have currently selected your normal tag file here, but this should be a different file containing only translations, else it will not work as intended. If you already have one downloaded you need to select it there, or else look for one (for example https://github.com/sgmklp/tag-for-autocompletion-with-translation, https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/discussions/23, or those linked in https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/issues/216#issue-1838667191).

Then it should look more like this
![image](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/assets/34448969/101aec06-5450-4a48-a0ad-898270232e93)

**Comment by DominikDoom** [comment]
Similarly, don't use danbooru.csv here.
![image](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/assets/34448969/6d670f62-d594-4984-80de-379d69e8de87)

That is only for small sets like the included "extra-quality-tags.csv". It will hinder functionality to use the main file there.
