### ISSUE TITLE
No longer seems to work with SD.Next in third party textboxes

### ISSUE THREAD

**Issue by Nalwonk** [DominikDoom/a1111-sd-webui-tagcomplete#244]
I don't get the tag complete window in any textboxes outside the Prompt/Negative Prompt box in From Image and From Text

It works perfectly fine within those boxes in those tabs, but it no longer works at all anywhere else.

**Comment by DominikDoom** [comment]
Can you tell me in which textboxes are affected / in which tabs you expect it to work?

Outside of t2i and i2i prompts, these are supported:
- Webui 1.6.0 style editor
- Image Browser filename/exif keyword search
- Various Dataset Tag Editor & WD Tagger textboxes
- Adetailer & Multidiffusion upscaler regional prompts

At least the first two are still working on my side.

Everything else isn't officially supported so far and would require the other extension's developers to check & register on their side.

**Comment by Nalwonk** [comment]
Dataset Tag Editor (specifically, I'd like it to work in Edit Caption, but it doesn't seem to work anywhere), and the Image Browser textboxes are no longer working on my end, but used to.

**Comment by DominikDoom** [comment]
Yeah, all gradio based textboxes are affected by it.
I initially tested Image Browser on the normal webui in case it stopped working without me noticing, but didn't remember to test it in SD.Next too before sending my questions. It's hidden for me there as well.

The easiest way to fix this is on SD.Next's side like I mentioned, also see the linked issue in the feed here for more info.
I imagine it won't take that long, but in the meantime you could add the following to your user.css file:
```css
.block.gradio-textbox {
    overflow: visible !important;
}
```
which should fix it in all textboxes.
The official fix will likely be the same or something similar.
