### ISSUE TITLE
Excuse me, what is the situation of garbled translation characters

### ISSUE THREAD

**Issue by kou201** [DominikDoom/a1111-sd-webui-tagcomplete#25]
![image](https://user-images.githubusercontent.com/55701610/196756827-0693b0e8-5a23-40f9-a94b-e7919fc37e7e.png)

It feels like a problem with text encoding, but I don't know how to solve it.

**Comment by sgmklp** [comment]
是使用了excle打开了.csv写入内容吗？
直接打开写入中文会导致乱码。请使用IDE或记事本打开

**Comment by sgmklp** [comment]
如果不是，也请使用IDE或记事本打开.csv文件，查看编码是否正常

**Comment by kou201** [comment]
> 如果不是，也请使用IDE或记事本打开.csv文件，查看编码是否正常

是在NGA搬了一个excel文档把内容改成了对应的格式然后修改后缀文件作为额外文件塞进去加载了……原来CSV文件还有这门道。有什么办法可以把excel文档转换成工作表文件吗？

**Comment by sgmklp** [comment]
复制你表格中有数据的列，然后粘贴到文本里，并自行添加逗号
Copy the columns with data in your table, paste them into the text, and add commas by yourself

**Comment by kou201** [comment]
> 复制你表格中有数据的列，然后粘贴到文本里，并自行添加逗号 Copy the columns with data in your table, paste them into the text, and add commas by yourself

明白了，感谢。

**Comment by sgmklp** [comment]
另外，对于翻译，请使用`"`包裹，否则内容可能因为`,`被截断
In addition, for translation, please use `"` package, otherwise the content may be truncated because of `,`

**Comment by sgmklp** [comment]
如果上述方法起作用了，不要忘记关闭这个Issuse,谢谢
If the above method works, don't forget to close the Issue. Thank you
