### ISSUE TITLE
不知道这里有没有人用秋叶整合包的,无论卸载重装还是各种设置都是弹不出来自动补全框

### ISSUE THREAD

**Issue by hrchrc** [DominikDoom/a1111-sd-webui-tagcomplete#252]
![捕获1](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/assets/37821354/28ab9b3a-6728-4882-8b61-aa3515db36b1)
![捕获2](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/assets/37821354/8c9cae44-a61a-43a4-8afa-6823eac0bee2)
![捕获3](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/assets/37821354/d73547dd-21d8-4d0f-9d8d-767b61653754)

**Comment by DominikDoom** [comment]
我对秋叶整合包的情况不太熟悉，但从我找到的资料来看，它似乎只是一个预打包版本，应该可以正常工作。
既然选项是可见的，也就意味着自动完成扩展启动正常。

你需要在两个地方检查是否有错误，并告诉我是否有任何错误。首先是 webui 启动时的终端窗口。其次是网页的浏览器控制台，可以用 CTRL+Shift+I 打开。

**Comment by lildorrpy** [comment]
一样的问题，我也是使用秋叶的整合包但是无论怎么重新下载插件都没办法使用tagcomplete，一样是没有自动补全框
![image](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/assets/87464423/481ae801-bbc8-42b0-9c5a-7813ef8113e1)
![image](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/assets/87464423/6a3709a6-f064-4bdf-95ea-e18bb373ed9e)
如图所示，我打了1gir但是并没有帮我补全，也没有框架
![image](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/assets/87464423/d2c0fd67-73a5-471e-9d84-c636f56791d4)
![image](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/assets/87464423/26b3a59c-688a-4d90-8078-686a4c060654)

**Comment by DominikDoom** [comment]
有多个 404 错误表明文件未找到/无法访问，但不仅仅是这个扩展名。
我认为您遇到了本地文件访问的一般问题。

这可能有多种原因。其一是广告拦截浏览器扩展，或者是 "Internet Download Manager" 高级浏览器集成插件。
另一个原因可能是您的安装不完整，实际上缺少了这些文件。
最后，如果您的扩展程序和其他用户数据存储在 webui 根文件夹之外的其他地方（例如其他驱动器上），则可能是权限错误。在这种情况下，你可能需要在 `--gradio-allowed-path` 命令行参数中添加该路径。

**Comment by lildorrpy** [comment]
非常感谢你的帮助！，我ban掉了idm和adblock所以的相关的插件tagcomplete插件可以正常使用了
![image](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/assets/87464423/b483235b-826c-4523-9d51-5508334e3cc4)
![image](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/assets/87464423/22ad4a88-93c3-45da-8a4c-2cd1b799e1ce)
非常感谢您抽出时间回复我！

**Comment by DominikDoom** [comment]
很高兴能帮上忙！

**Comment by hrchrc** [comment]
> 非常感谢你的帮助！ ，我ban掉了idm和adblock所以的相关的插件tagcomplete插件可以正常使用了 ![image](https://user-images.githubusercontent.com/87464423/283996057-b483235b-826c-4523-9d51-5508334e3cc4.png) ![image](https://user-images.githubusercontent.com/87464423/283996090-22ad4a88-93c3-45da-8a4c-2cd1b799e1ce.png) 非常感谢您抽出时间回复我！

我日了,抽空回来看了一下原来我的问题和你一样,我关了idm就可以了

**Comment by hrchrc** [comment]
> 很高兴能帮上忙！

谢谢您的回复,我的旧问题和新的提问人问的问题是一样的,我关了IDM插件就可以了弹出提示词了....
Thank you for your reply, my old question and the new questioner's question are the same, I can turn off the plugin and pop up the prompt word

**Comment by hrchrc** [comment]
> > 非常感谢你的帮助！ ，我ban掉了idm和adblock所以的相关的插件tagcomplete插件可以正常使用了 ![图像](https://user-images.githubusercontent.com/87464423/283996057-b483235b-826c-4523-9d51-5508334e3cc4.png) ![图像](https://user-images.githubusercontent.com/87464423/283996090-22ad4a88-93c3-45da-8a4c-2cd1b799e1ce.png) 非常感谢您抽出时间回复我！
> 
> 我日了,抽空回来看了一下原来我的问题和你一样,我关了idm就可以了

要是我一个个插件我也慢慢敲英文我真的想死

**Comment by DominikDoom** [comment]
@hrchrc 啊，对不起，我没注意到其他回复不是您写的。很高兴知道该解决方案也为您解决了问题。对于中国用户来说，这似乎是一个出乎意料的常见问题。

**Comment by hrchrc** [comment]
> @hrchrc 啊，对不起，我没注意到其他回复不是您写的。很高兴知道该解决方案也为您解决了问题。对于中国用户来说，这似乎是一个出乎意料的常见问题。

是的,在我们中文社区关于您的插件和"秋叶整合包"有不少人在使用,而且也有一部分人使用这个整合包出现了类似我们两个这个情况; 
 
如果可以的话,能不能在中文的readme里提示一下使用"秋叶整合包"版stable diffusion的人使用时记得**关闭**浏览器扩展的idm=Internet Download Manager插件,我在Google浏览器和edge浏览器尝试过,只要关闭浏览器的IDM插件,就可以在这个整合包里面正常运行您的插件;主要是使用"秋叶整合包"的中国人数量不少

**Comment by DominikDoom** [comment]
说得好，我已经在 ["常见问题 & 已知缺陷"](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/blob/main/README_ZH.md#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98--%E5%B7%B2%E7%9F%A5%E7%BC%BA%E9%99%B7) 部分添加了警告说明。

**Comment by hrchrc** [comment]
> 说得好，我已经在 ["常见问题 & 已知缺陷"](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/blob/main/README_ZH.md#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98--%E5%B7%B2%E7%9F%A5%E7%BC%BA%E9%99%B7) 部分添加了警告说明。

非常感谢您肯接受我的建议,谢谢!!
