### ISSUE TITLE
Wildcard autocompletion in the prompt box cutoff from colon

### ISSUE THREAD

**Issue by Yinzo** [DominikDoom/a1111-sd-webui-tagcomplete#267]
## Describe the bug
After dynamic prompts is installed, we can get wildcard autocompletion in the prompt box. It works most of time except there are colons ":" in the prompts, it will just cuts off the prompt, only offer the text after the first colon.

## To Reproduce
using this test file:
```
$cat test.txt
1girl, trailblazer \(honkai: star rail\), honkai star rail
```

## Expected behaviour
Autocomplete offer the whole prompt: `1girl, trailblazer \(honkai: star rail\), honkai star rail`

## Captures
Here is the autocomplete shows for the test.txt before apply
![1](https://github.com/adieyal/sd-dynamic-prompts/assets/7458082/0554663a-4590-4bf4-8724-1d5af482e960)

Here is the autocomplete result after apply
![2](https://github.com/adieyal/sd-dynamic-prompts/assets/7458082/5ac780a8-7cf4-487b-b154-210729ab791b)

**Comment by DominikDoom** [comment]
Fixed, this was caused by a broken sanitization rule. I just removed it since it was a remnant from a really early version and not needed anymore.
