### ISSUE TITLE
Request: Scrollable tag lists

### ISSUE THREAD

**Issue by Klokinator** [DominikDoom/a1111-sd-webui-tagcomplete#27]
When autocompleting tags with this tool, it seems to max out at 5 or so tags. But if I search for Hair, I might want to scroll down with the down arrow and load more tags, if present. Maybe that option could be added somehow?

![image](https://user-images.githubusercontent.com/30022758/196871347-56ea06f8-2907-4659-b8e7-3a8121df5c69.png)

**Comment by sgmklp** [comment]
endale the `showAllResults`

**Comment by Klokinator** [comment]
Well I feel stupid. Thanks!

**Comment by DominikDoom** [comment]
You need to edit the `config.json` file which should be in your tags folder.
To add a bit to it, there are three relevant settings for this: `maxResults`, `resultStepLength`, and `showAllResults`.

If you enable `showAllResults`, it will only load the amount specified in `resultStepLength` at once to prevent lag. It will load more if you reach the end of the list, but the standard amount of 500 is pretty big so should only matter for the very first few letters you type where a lot of tags still match. Even with `showAllResults` set to true, `maxResults` will still have an effect. It determines the maximum height of the box before it starts scrolling, so you can still set how many lines should be visible at once.

**Comment by DominikDoom** [comment]
@Klokinator I'm closing this issue as stale, feel free to re-open it if you still have issues with this.

**Comment by Klokinator** [comment]
Totally fine! Sorry, I didn't realize I had to mark it as anything. You answered my question, Dominik.

**Comment by DominikDoom** [comment]
No problem, just want to keep the issue list small :D
