### ISSUE TITLE
Is it possible to update danbooru.csv?

### ISSUE THREAD

**Issue by wtre59** [DominikDoom/a1111-sd-webui-tagcomplete#274]
- The available csv data is limited to 2022, and danbooru has shut down their api, but there is a dataset on Huggingface: **danbooru2023**, and these json files seem to contain tag-related information.

- [https://huggingface.co/datasets/nyanko7/danbooru2023/tree/main/metadata](url)

> Unfortunately, I know next to nothing about programming, and there doesn't seem to be any software here that can easily extract the required data in a code-free manner.

- Considering when the SDXL model was introduced, a model based on SDXL fine-tuning should have been trained using a lot of data from 2023.

> And danbooru's tag database (mainly post count) also seems to have been updated on a fairly large scale during the year.

- Using post count to determine if the concept of the tag was able to be trained into the model to make it comprehensible should work for most large dataset models.

That's it, thanks for developing this extension, it's quite useful.

**Comment by DominikDoom** [comment]
Thanks for the link, I will take a closer look at it later. From a quick glance, it seems to be similar enough in structure to the data I originally used. I just need to convert it for the extension.

I'll compare it to the current dataset and determine if it's worth updating regarding post count changes and new tags. Many of the new tags will have very little post counts though and would not be included anyway, but the count changes to existing tags should be no problem.
