### ISSUE TITLE
可以自己选择排序方式吗？

### ISSUE THREAD

**Issue by aiwandexiong** [DominikDoom/a1111-sd-webui-tagcomplete#28]
比如我想补全solo，但即使4个字母都打出来也没有出现想要的选项，得往下翻，可以自选怎么按照标签类型排序吗？
![image](https://user-images.githubusercontent.com/112748580/197085068-4d08f567-dc0a-4348-849a-d23acf7e443d.png)

还有，可以按照字母顺序补全吗，比如我输入cat，补全就首选前三个字母是cat的
![image](https://user-images.githubusercontent.com/112748580/197086031-14ab221c-cbdc-45a4-986b-30fd5e45c4ae.png)

[我用google机翻了下tag，基本可以凑或用，中文好像得以utf-8保存，不然会乱码
[danbooru.csv](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/files/9834821/danbooru.csv)

**Comment by sgmklp** [comment]
作为临时的解决方案，使用excle将Tag表格排序应该能够让情况更好一点。
As a temporary solution, using excle to sort the Tag table should make the situation better.

**Comment by batvbs** [comment]
我的提交可以解决这个问题。
https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/pull/75

**Comment by DominikDoom** [comment]
Fixed by 894335f1dead68cf82ae147d3e53b37abe8fb597.
