### ISSUE TITLE
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.

### ISSUE THREAD

**Issue by 158zd** [DominikDoom/a1111-sd-webui-tagcomplete#281]
Could not locate model-keyword extension

**Comment by DominikDoom** [comment]
This is not an error, just an info notice.

Tag autocomplete can use the keyword lists for Lora provided by https://github.com/mix1009/model-keyword, to add known trigger words if you insert a lora name through autocompletion. These lists are built from the data provided by model creators/uploaders on Civitai. The extension doesn't need to be active / complete, tag autocomplete just uses the [lora-keyword.txt](https://github.com/mix1009/model-keyword/blob/main/lora-keyword.txt) file. You can also download that on its own and put it in any subfolder in /extensions if you want to.

The notice is just saying that without that list, it can only fill in the activation keywords you entered yourself through the webui interface.

You can read more about it here: https://github.com/DominikDoom/a1111-sd-webui-tagcomplete#lora--lyco-trigger-word-completion
