### ISSUE TITLE
3.0.0无法弹出tag选项框

### ISSUE THREAD

**Issue by trojan-uma** [DominikDoom/a1111-sd-webui-tagcomplete#282]
目前已测试SDwebui 1.8/1.9版，3.0.0版的插件在这两个版本内无法在输入tag时弹出补全选项框

**Comment by DominikDoom** [comment]
终端窗口或浏览器控制台是否显示错误？我在这些版本上没有遇到问题。

**Comment by trojan-uma** [comment]
> 终端窗口或浏览器控制台是否显示错误？我在这些版本上没有遇到问题。

并没有报错，并且在更新之前上一个版本（2.12）还是正常运作（在SDwebui 1.8/1.9下）

`Python 3.10.14+ (heads/3.10:812245ecce, Mar 30 2024, 12:10:58) [MSC v.1939 64 bit (AMD64)]
Version: v1.8.0
Commit hash: bef51aed032c0aaa5cfd80445bc4cf0d85b408b5
Launching Web UI with arguments: --medvram-sdxl --theme dark --port 65500 --xformers --xformers-flash-attention --opt-channelslast --api
CHv1.8.4: Get Custom Model Folder
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
[-] ADetailer initialized. version: 24.4.1-dev.0, num models: 21
dirname:  W:\stable-diffusion-webui\localizations
localizations:  {'I18N_sd-webui-zh_CN': 'W:\\stable-diffusion-webui\\localizations\\I18N_sd-webui-zh_CN.json', '简体中文语言包_RunawayOrange': 'W:\\stable-diffusion-webui\\extensions\\SD-WebUI-Localization_ZH_CN\\localizations\\简体中文语言包_RunawayOrange.json'}
ControlNet preprocessor location: W:\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2024-04-13 22:24:51,947 - ControlNet - INFO - ControlNet v1.1.443
2024-04-13 22:24:52,137 - ControlNet - INFO - ControlNet v1.1.443
sd-webui-prompt-all-in-one background API service started successfully.
[DanTagGen]-INFO: Llama-cpp-python/gguf model loaded
Loading weights [c936130834] from W:\stable-diffusion-webui\models\Stable-diffusion\C\2D\nordrinLittleLittle_v30.safetensors
Creating model from config: W:\stable-diffusion-webui\configs\v1-inference.yaml
2024-04-13 22:24:58,943 - ControlNet - INFO - ControlNet UI callback registered.
Loading VAE weights specified in settings: W:\stable-diffusion-webui\models\VAE\vae-ft-mse-840000-ema-pruned.safetensors
Applying attention optimization: xformers... done.
Model loaded in 7.5s (load weights from disk: 1.0s, create model: 0.8s, apply weights to model: 3.6s, apply channels_last: 0.1s, apply half(): 0.2s, load VAE: 0.5s, move model to device: 0.3s, load textual inversion embeddings: 0.5s, calculate empty prompt: 0.3s).
CHv1.8.4: Set Proxy: http://127.0.0.1:8084
Running on local URL:  http://127.0.0.1:65500

To create a public link, set `share=True` in `launch()`.
🤯 LobeTheme: Initializing...
[sd-webui-prompt-all-in-one] Loading model facebook/mbart-large-50-many-to-many-mmt from W:\stable-diffusion-webui\extensions\sd-webui-prompt-all-in-one\models...
[sd-webui-prompt-all-in-one] Model facebook/mbart-large-50-many-to-many-mmt loaded.
Startup time: 63.7s (prepare environment: 7.6s, import torch: 4.4s, import gradio: 0.8s, setup paths: 3.1s, initialize shared: 0.4s, other imports: 0.5s, list SD models: 5.0s, load scripts: 7.4s, refresh VAE: 0.1s, create ui: 8.3s, gradio launch: 3.4s, add APIs: 1.1s, app_started_callback: 21.4s).`

**Comment by DominikDoom** [comment]
打开浏览器控制台（CTRL+SHIFT+I），然后在输入提示时保持打开状态。是否有错误显示？

**Comment by trojan-uma** [comment]
> 打开浏览器控制台（CTRL+SHIFT+I），然后在输入提示时保持打开状态。是否有错误显示？

有，见下图

![Snipaste_2024-04-13_23-12-00](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/assets/33084797/0bb8f818-a0d4-46d7-abc9-8b88e35020a5)

**Comment by DominikDoom** [comment]
这里的错误是由 "weight_helper.js "记录的，它不是这个扩展中的一个文件，但看起来它干扰了功能。你能查一下这个文件来自哪里吗？可能是其他扩展引起的问题。

**Comment by DominikDoom** [comment]
在 webui 中，扩展并不是孤立的，因此如果两个函数的名称相同，它们就会互相覆盖。我猜就是这种情况，导致问题的扩展很可能是在 TAC 之后加载的，并覆盖了我的函数。
如果这个猜测是正确的，我就可以通过给我的函数取一个更独特的名字来解决这个问题。

**Comment by trojan-uma** [comment]
冲突插件来自
sd-webui-weight-helper
https://github.com/nihedon/sd-webui-weight-helper

**Comment by DominikDoom** [comment]
我已经应用了重命名修复，如果解决了，请告诉我。

**Comment by trojan-uma** [comment]
> 我已经应用了重命名修复，如果解决了，请告诉我。

插件已经正常工作（SDWebui 1.8），Orz

**Comment by zsnzzg** [comment]
> 我已经应用了重命名修复，如果解决了，请告诉我。

我也遇到了。。。1.9.4  至今还不能正常启用    英文也不行

**Comment by zsnzzg** [comment]
> > 我已经应用了重命名修复，如果解决了，请告诉我。
> 
> 我也遇到了。。。1.9.4 至今还不能正常启用 英文也不行

![2024-6-4 16-5-16](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/assets/112025678/928f6d62-fac1-4d9f-a15b-87e4bd164c21)
![2024-6-4 16-1-17](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/assets/112025678/b427deb0-3cb7-4aea-9428-cfda29ec2569)
报错是看这里的吗？

**Comment by DominikDoom** [comment]
@zsnzzg 您的问题与此无关。浏览器控制台中的错误意味着在以下两个扩展设置中，有一个输入了错误的文本。

![image](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/assets/34448969/949cadeb-0e95-4f96-995a-0b8299b03016)

我还知道，在过去，一些用于翻译的浏览器扩展会错误地修改这些内容，如果您之后保存了设置，就会导致此错误。
请将这些设置的文本复制到 JSON 验证器中查找潜在问题，或通过在 webui 安装根目录下打开 config.json 并删除 tac_keymap 和 tac_colormap 行来重置这些设置。

如果您无法自行解决该问题，请打开一个新问题，因为该问题与上述修复无关。
