### ISSUE TITLE
Broken Text (Encoding issue?) in A1111

### ISSUE THREAD

**Issue by DominikDoom** [DominikDoom/a1111-sd-webui-tagcomplete#304]
### Discussed in https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/discussions/303

<div type='discussions-op-text'>

<sup>Originally posted by **gitupp22** October  6, 2024</sup>
Today when typing in A1111, I get strange symbols instead of the words usually given. When typing the number 1, instead of something like 1girl popping up, it says �?���U��qk�1s5v��vV��1��ccJ4�ذ�<������d\[�}��f��ݶ����D�V'�, 

The only tags that seem to work are the quality tags from extra-quality-tags.csv. It's a small list, so I decided to try and delete all tags except a few from the danbooru.csv file and it works as long as there are only about 5 tags in there.

I tried reinstalling. It is still working for me in ForgeUI, but not in Automatic1111.
![image](https://github.com/user-attachments/assets/0961a662-1e11-4305-a3bb-04841e1b9e4a)
</div>

**Comment by DominikDoom** [comment]
@gitupp22 Like I also mentioned in the other issue, this looks like an encoding issue. But that is unusual since I already load everything with UTF-8 to support non-ASCII characters, and it would make no sense in that case that it works in Forge but doesn't in base A1111. I don't load the files with any webui specific method that could change between them.
Another possibility would be that the file is corrupted or doesn't get parsed correctly, but that also wouldn't explain it only being broken in A1111.

The main things I need to know:
- You said "today", so did this start only recently? If so, do you remember what changed? Was it a webui update or did you update TAC itself, or other extensions?
- Any errors visible in the terminal window?
- Any errors in the browser console? (Press CTRL-SHIFT-I while on the webui page)
- Also in the browser developer tools like the console, switch to the "Network" tab and reload the page afterwards. Are any files in the list there failing to load (red)?
- What language is your browser set to, and do you use any translation extensions for A1111?

**Comment by gitupp22** [comment]
I believe I figured out the problem. I added a CSV reader extension to chrome to read my payment spreadsheets. It must have been translating the information from the CSV files of the extension.

Thank you for your suggestion to look into the browser. When I tried incognito mode it worked, so I guessed it must have been an extension. Disabling the extension lets the tags work properly again.

**Comment by DominikDoom** [comment]
Glad to hear you were able to solve it! TAC is roughly 70/30 browser based (JavaScript) vs local python code, so it's common for browser extensions or settings to mess something up, especially regarding file loading. I also encountered issues in the past where a popular download manager extension was blocking local file requests for some users.

Btw, in case you only need your CSV reader extension for specific sites, you can change the extension settings in chrome to enable it only there, i.e. a whitelist. So you don't have to toggle it on or off manually. The other way around (disabling only on the webui site) sadly isn't a built-in feature.
