### ISSUE TITLE
Left and right arrow shouldn't focus the autocomplete popup

### ISSUE THREAD

**Issue by thojmr** [DominikDoom/a1111-sd-webui-tagcomplete#31]
Any time I'm trying to correct a spelling mistake with left and right arrow it focuses the popup instead.

I would expect that the up and down arrow keys would function to select from the autocomplete popup.  Not the left and right arrows.

**Comment by DominikDoom** [comment]
Left and right arrow jump to the first/last result of the list, which is useful for long lists. But since multiple people have asked about it, I will make that feature optional. In the meantime, you can press Escape to close the popup as a workaround.
