### ISSUE TITLE
Request: Autocomplete support for wildcards extension in A111

### ISSUE THREAD

**Issue by Evil-Dragon** [DominikDoom/a1111-sd-webui-tagcomplete#35]
I've been told this is an issue with autocomplete not supporting the new wildcards extension version of A111. See more at: https://github.com/AUTOMATIC1111/stable-diffusion-webui-wildcards/issues/1

Wildcards are also now stored in extensions\wildcards\wildcards.
Autocomplete only checks inside \scripts\wildcards

Many thanks.

**Comment by DominikDoom** [comment]
Good to know, I'll add that as well.
One problem though is that the user can technically call the extension folder however they want, so for now I'll only support it in extensions\wildcards\wildcards like you said. I'll probably add a custom path config option later for that case.
