### ISSUE TITLE
Token of embedding that has some special characters can't be recognized

### ISSUE THREAD

**Issue by byzod** [DominikDoom/a1111-sd-webui-tagcomplete#36]
I got a embedding in png format, its token is something like `emb_1.5`

This embedding can't be recognized and not shown in the tag drop down list when type `<` (yes, it can be used correctly and recognized by the `Train` tab), I don't know how to change the token, changing the filename is not working, only `emb_1.5` can active that embedding

I'm not sure legal characters for token of embedding, maybe other characters also triggers this bug but I don't know

p.s. Can you tell me about the `<embedding name>` thing? I think I saw this angle brackets syntax somewhere before but I can't find it now in wiki of a1111's webui [here ](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Features) or [here](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Textual-Inversion), did this syntax removed or something? Or is this a tagcomplete feature?

**Comment by DominikDoom** [comment]
I just tested with a png embedding file of that name, it works for me.
Are you using the latest version? I added support for png embeddings only earlier today because I originally forgot about them when that feature was added.

**Comment by DominikDoom** [comment]
> Maybe it's related to that I didn't ctrl+F5 refesh the page since other png embeddings is loaded

If you added the problematic embedding after the working one, that would make sense. The script reads from the temporary files, and the browser caches those from time to time too, so it could be that it just didn't use the version of that temp file with the new embedding listed.
