### ISSUE TITLE
support for the wildcards extension doesn't work by default

### ISSUE THREAD

**Issue by djkacevedo** [DominikDoom/a1111-sd-webui-tagcomplete#37]
You use extensions/wildcards/wildcards
Following the instructions on the wiki page will by default have wildcards at extensions/stable-diffusion-webui-wildcards/wildcards

**Comment by DominikDoom** [comment]
I know that it currently only works for that one path, but I'm not aware of any default or suggested path for that folder, the user can choose the name themselves when cloning. Hence, I noted that the folder might need to be renamed for support at the moment.
The wiki only shows
```bash
git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui-aesthetic-gradients extensions/aesthetic-gradients
```
as an example, which clearly has a custom folder name as the second argument which is different from the repo name. So the name you said above only applies if you manually download and paste it there or clone inside the extensions directory without specifying that second part.

This isn't meant to downplay the issue, but my script can't know what you called your folder and my reasonable guess was to name it the same as the old script, just wildcards. So in the meantime you will just have to rename it.
I plan to add either a config option for a custom path or searching for a wildcards folder in any extension folder no matter the name later, which should resolve this anyway.

**Comment by djkacevedo** [comment]
True... I didn't notice that he renamed it when he cloned :(, and then the other extensions, like the image browser, doesn't do that.

Another option is to add that path to your config file. That's actually the first thing I looked for when it wasn't picking up my wildcards.

**Comment by DominikDoom** [comment]
Yeah I plan to experiment with it tomorrow, then I'll add either a config option or automatic detection depending on how easy/performant the latter is.
With some quick searching earlier, auto-detection might be easier than I first thought, since I already have a similar structure in place for nested wildcard folders in case users have them grouped by categories that way.

**Comment by Evil-Dragon** [comment]
This was my fault for renaming it from the standard convention to wildcards, perhaps it is better called "stable-diffusion-webui-wildcards" in this script so it is consistant for everyone. Sorry for the trouble caused.

**Comment by DominikDoom** [comment]
No worries, I probably would have called it that either way, since I like the extension names to be shorter.

**Comment by evanjs** [comment]
> There is a case for actually scanning other extensions and checking if there are wildcards folders there, see this extension https://github.com/Klokinator/UnivAICharGen/tree/master/wildcards

Thanks for sharing. Been thinking about a more guided approach like this for a while now.
Would be happy to see this type of configuration fully supported by both tagcomplete and [dynamic-prompting](https://github.com/adieyal/sd-dynamic-prompting).
