### ISSUE TITLE
Have problem detecting newlines in prompt

### ISSUE THREAD

**Issue by byzod** [DominikDoom/a1111-sd-webui-tagcomplete#44]
tagcomplete works perfectly everywhere in prompt in one line, for example `cat, dog, girl`

But with newlines (which is valid for webui), it has problem handling it

For example in prompt:

```
cat, dog,⛔
⛔girl
```

tagcomplete is not working in position of `⛔` mark, while it's working in position of `✅` mark

```
cat, dog,✅girl
```

demo:
![An1](https://user-images.githubusercontent.com/848607/198686880-b5ac128c-176d-420d-a800-1bdd44e4236d.gif)

**Comment by DominikDoom** [comment]
Good catch, the regex didn't match anything in that case because newlines weren't trimmed out of the search word.
As long as the tag is on the same line, it should work now.
