### ISSUE TITLE
Menu does not showk when a () prompts exist

### ISSUE THREAD

**Issue by Woleskill** [DominikDoom/a1111-sd-webui-tagcomplete#50]
I had downloaded the latest version through the Git clone that puts it into the extensions folder.
Ever since it only works when there are no () prompts anywhere in the positive ones.

As soon as you add one at any spot it just breaks and does not show the menu anymore. And that's when you try and add one before or after a () prompt. 

Not a cache issues since that's cleared. Originally i had it in my Stable Diffusion folder itself and that worked without issues. Those files are gone now since i replaced it with a fresh git clone into the extensions folder.
Also running this Locally on a Linux machine, if that matters.

**Comment by DominikDoom** [comment]
Are you using the most up to date version? There was a bug regarding parentheses but that should have been fixed in the last three commits.

**Comment by Woleskill** [comment]
Welp. Must have downloaded right before the fix. Did another git pull and now it works. 
Thanks for the quick reply and fix!

**Comment by DominikDoom** [comment]
No worries, my fault for pushing a broken fix without noticing in the first place!
That bug haunted me for a solid two hours. I was really starting to doubt my sanity if it was still broken after two hotfixes, haha
