### ISSUE TITLE
Can't autocomplete Chinese characters

### ISSUE THREAD

**Issue by liggest** [DominikDoom/a1111-sd-webui-tagcomplete#51]
Normally, the tag autocomplete works perfectly
examples below use the word ninja (忍者)
![normal_typing](https://user-images.githubusercontent.com/43201720/198868307-c9d0664b-1a1b-4469-ba34-a0c4d262eaba.gif)
But autocomplete dosen't show up after stop inputting Chinese characters
![typing](https://user-images.githubusercontent.com/43201720/198868455-4c429ebb-2013-49fc-9f0d-3fb624be71b9.gif)

Generally, Chinese native speakers use some kinds of input methods (or 输入法) as an assistance to input Chinese characters
After typing alphabet representations, one could choose right characters by pressing number keys or space (for current choice) or enter(for reserving inputted alphabets)
As shown above, autocomplete dosen't seem to work in these kinds of occasions. I vaguely remember that it was working few versions ago, but I'm not sure about how to test again

In additional, autocomplete for deleting seems to have similar problem
![normal_delete](https://user-images.githubusercontent.com/43201720/198868870-bb89a88d-0539-4ed7-910d-69344c22203c.gif)
![delete](https://user-images.githubusercontent.com/43201720/198868875-45346bf4-8e32-4c4c-a7fa-a5181f760360.gif)

**Comment by DominikDoom** [comment]
I don't have a Chinese IME installed so I can't test it at the moment, but I'll try it out later if I have time.

If you want to try out older versions to see where it stopped working, you can find them in https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/releases. That would definitely be helpful.

Also please check if searchByTranslation is true in your config, that should be the only relevant option.

**Comment by liggest** [comment]
> Also please check if searchByTranslation is true in your config, that should be the only relevant option.

It's true by default and I haven't changed it

> If you want to try out older versions to see where it stopped working, you can find them in https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/releases.

Thanks for providing this, it helps a lot. Maybe I'll try them later

**Comment by DominikDoom** [comment]
I just had a look in the code again and am pretty sure I found the issue, before 1.9.0 should work.
I will fix it later today. It's related to the updated regex after 1.9.0 not correctly matching words starting with non-ascii characters.

**Comment by liggest** [comment]
> I just had a look in the code again and am pretty sure I found the issue, before 1.9.0 should work.

I've just tried version hotfix 1.8.2, it works for me, so I think you're right

> I will fix it later today. It's related to the updated regex after 1.9.0 not correctly matching words starting with non-ascii characters.

Thanks for updating so quickly!
