### ISSUE TITLE
(possible regression bug) Tag list not shown in `(<tag>)`, `[<tag>]`, `(<tag>:1.2)` syntax

### ISSUE THREAD

**Issue by byzod** [DominikDoom/a1111-sd-webui-tagcomplete#59]
Tagcomplete version: https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/commit/92a08205d05e98a54215d8b2ffeadd19a01cfd3d

1. Editing tag in weight parenthesis and no tag list shown, different from the [demo here](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/issues/47#issuecomment-1295827356).

2. Editing tag in simple weight syntax (`(<tag>)`, `[<tag>]`) and no tag list shown unless blanks before and after the tag.
   When edit `cat` in `(cat)` (alias of `(cat:1.1)`), it searchs `(cat)` exactly, only tags like `chen_(cat)` matches but `cat_ears` do not.
   ![An1](https://user-images.githubusercontent.com/848607/199216779-62f03cf2-3021-41b2-87af-e654eade4d18.gif)

   discussion: tag can and many of them do have parenthesis, but that's not needed when speaking of searching at most of times, for example `cat` have hundreds of related tags while `(cat)` is a valid tag component too but have only 9 matches out of 10k tags.
   So maybe it's safe (or to say tolerable) to ignore parenthesis of user input?

**Comment by DominikDoom** [comment]
You are correct, seems to be a regression introduced by an oversight in e49862d4228ad0f1a3691a9afeb1b05ff119108d.
It's an easy fix luckily, will push it in a moment.

> discussion: tag can and many of them do have parenthesis, but that's not needed when speaking of searching at most of times, for example cat have hundreds of related tags while (cat) is a valid tag component too but have only 9 matches out of 10k tags.
So maybe it's safe (or to say tolerable) to ignore parenthesis of user input?

Problem is that with the current way I replace/insert the completed text, it needs to match what the user typed 1:1, else it won't find what region to replace. So if we ignore parentheses while typing, replace will likely not work, and an "approximate match" is pretty hard to do properly.
