### ISSUE TITLE
Script doesn´t work for me

### ISSUE THREAD

**Issue by TripleKiller666** [DominikDoom/a1111-sd-webui-tagcomplete#6]
Javascript File is in the right place, and so is the "tags" Folder (btw both Version 1.4.2)

(index):80 Cannot read properties of null (reading 'querySelector') TypeError: Cannot read properties of null (reading 'querySelector')

Yet there is no popup or anything showing up when I load the Web-UI.

I even tried it with another Browser (default Firefox, other being Chrome) and the result is the same.

**Comment by TripleKiller666** [comment]
Firefox shows lots of Errors:

Uncaught TypeError: source.indexOf is not a function

**Comment by DominikDoom** [comment]
Are you using the newest webui & script version?

**Comment by TripleKiller666** [comment]
Yeah about that...

Thought that "git pull" in my bat file would automatically pull new commits.
But it didn´t.

Now everything works with the new WebUI and your latest Version.
Really sorry about that trouble mate!
