### ISSUE TITLE
Feature Request: Ask A111 to add this as an extension

### ISSUE THREAD

**Issue by Evil-Dragon** [DominikDoom/a1111-sd-webui-tagcomplete#61]
A111 now has the ability to have scripts and javascript to be added as an extension without having to have scripts and javascript populate outside of [basedir]/extensions/extension-name

It also offers the ability to update from github from inside A111.

I've done a quick test of your script loaded as an extension and as far as I can tell it all works like normal.

You might want to consider asking Automatic1111 to add your script to the list located at: https://raw.githubusercontent.com/wiki/AUTOMATIC1111/stable-diffusion-webui/Extensions-index.md

**Comment by DominikDoom** [comment]
Yeah, I added support for extension installation around a week ago and have it as the recommended install method in the README (at least the English one).
I guess I can ask him to put it there as well, true.

**Comment by DominikDoom** [comment]
Done, thanks for the reminder.
https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Extensions#booru-tag-autocompletion
