### ISSUE TITLE
Long tags with alias/translation not fully visible

### ISSUE THREAD

**Issue by byzod** [DominikDoom/a1111-sd-webui-tagcomplete#65]
![1](https://user-images.githubusercontent.com/848607/200132977-ffd17aeb-c1c2-4fdc-84bb-f8502a22fe93.jpg)

**Comment by byzod** [comment]
![b1](https://user-images.githubusercontent.com/848607/200152797-968ba93a-08c4-4b59-8345-3cce8603c510.jpg)
It's still covered, maybe covered by the tag count?

**Comment by DominikDoom** [comment]
Interesting, it only seems to happen on Firefox. It probably handles some part of the CSS differently, I'll have a look.

![image](https://user-images.githubusercontent.com/34448969/200172268-4228e1ea-bec4-4f82-9014-b54893361174.png)
![image](https://user-images.githubusercontent.com/34448969/200172323-d235ef03-7b28-4ba5-a384-2364dd43b3b3.png)

**Comment by DominikDoom** [comment]
Found the issue, it seems that Firefox by default doesn't include the scrollbar in its width/text overflow calculation, causing it to clip despite having no maximum width. After explicitly setting `scrollbar-gutter` to stable in the CSS, it seems to work. Will push in a minute.
