### ISSUE TITLE
I need a hand to install the extension in colab

### ISSUE THREAD

**Issue by Juan-Cruz-Iturrioz** [DominikDoom/a1111-sd-webui-tagcomplete#67]
Hello i'm user https://colab.research.google.com/github/TheLastBen/fast-stable diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb

And I get this message
<img width="1368" alt="Captura de pantalla 2022-11-07 a las 14 10 35" src="https://user-images.githubusercontent.com/89535004/200372043-a920a4cc-a063-466e-b72a-f2cd07e9895c.png">

Error loading script: tag_autocomplete_helper.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 170, in load_scripts
    exec(compiled, module.__dict__)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/tagcomplete/scripts/tag_autocomplete_helper.py", line 77, in <module>
    write_tag_base_path()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/tagcomplete/scripts/tag_autocomplete_helper.py", line 63, in write_tag_base_path
    f.write(TAGS_PATH.relative_to(FILE_DIR).as_posix())
  File "/usr/lib/python3.7/pathlib.py", line 900, in relative_to
    .format(str(self), str(formatted)))
ValueError: '/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/tagcomplete/tags' does not start with '/content/gdrive/MyDrive/sd/stable-diffusion'

how can it work?

**Comment by DominikDoom** [comment]
Have a look at this, it worked for another user recently:
https://github.com/TheLastBen/fast-stable-diffusion/issues/409#issuecomment-1304741272

> in the last cell, change
> 
> ```
> with capture.capture_output() as cap: 
>   %cd /content/gdrive/MyDrive/sd/stable-diffusion-webui
> ```
> 
> to
> 
> ```
> with capture.capture_output() as cap: 
>   %cd /content/gdrive/MyDrive/sd/stable-diffusion
> ```
> 
> let me know if it works so I'll revert the pull request

**Comment by Juan-Cruz-Iturrioz** [comment]
Thank you, now working

**Comment by konqiDAM** [comment]
The new fix for me seems to be 
```
with capture.capture_output() as cap: 
  %cd /content/gdrive/MyDrive/sd/stable-diffusion-webui
```
For https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb
![image](https://user-images.githubusercontent.com/44301655/204244041-e6ad3970-dca6-42e7-8fe4-d4632282f6f9.png)

But I don't understand why there are two folders and why it start in one and not the other were extensions are installed. I'm not sure if this is an actual fix, probably going to ask in automatic1111 repo.
