### ISSUE TITLE
[Request] Hide "Autocomplete options" and persist settings after restart

### ISSUE THREAD

**Issue by onusai** [DominikDoom/a1111-sd-webui-tagcomplete#68]
I would like an option to hide the "Autocomplete options" in the settings tab
It would also be nice if the changes made to these options were saved to persist after restarting the webui

**Comment by DominikDoom** [comment]
You can already hide the options using the script's config.json file, as well as set the starting value for appendCommas there too. It's not really persisting but I didn't feel the need so far to change it too often between restarts (although I will definitely have a look at proper persistence in the future).

**Comment by onusai** [comment]
my bad I should have checked, I wasn't aware of the config file. this extension is really great, thanks a lot for all your effort!
