### ISSUE TITLE
Problem displaying tag in <li> if tag starts with <

### ISSUE THREAD

**Issue by nobodynuf** [DominikDoom/a1111-sd-webui-tagcomplete#7]
Hello,

I was making a custom tags file, and added my embeddings (textual_inversion) as tags in the form "<name_embedded>" to enable autocompletion and stuff.

After editing my target csv file I noticed that the autocomplete function filters correctly but does not show the element in the list (the tag <name_embedded> appeared like '' )

I resolved the issue escaping the < and the > symbols with the html equivalent.

The line I edited 
https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/blob/fbfc988fe52904da006f372d89ee576cc4e5bdf0/tagAutocomplete.js#L272

was replaced with
`        li.innerHTML = result[0].replace('<','&lt;').replace('>','&gt;');
`
and the issue is solved.

I mean, I know that the custom script is based on danbooru tags but maybe the scripts need html escaping to avoid those types of issues.

**Comment by DominikDoom** [comment]
Good point, I totally didn't think about HTML entities in tags. Will fix later.

**Comment by DominikDoom** [comment]
Should be solved now! Let me know if it still behaves unexpected for you.
