### ISSUE TITLE
About the new config system...

### ISSUE THREAD

**Issue by etherealxx** [DominikDoom/a1111-sd-webui-tagcomplete#81]
First of all, thank you for DominicDoom & team for making and mantaining this extension. This really helps a lot.

So i usually use colab for webui. And i use some script to change settings of your ext easily, by editing the config.json. Like this one for example, toggling the showAllResult
![2022-11-28 08_12_24-anythingv3 ipynb - Colaboratory](https://user-images.githubusercontent.com/64251396/204173784-75d8449f-a169-4fd1-aa67-b30d9d84a339.jpg)

However the new config system removed the config.json. Sure, the new system are easier to understand for beginners who wants to change the settings. But i lost the ability to change it easily via code (it might still be possible, but i don't know where the exact position of the settings is located)

My own temporary solution is by using git checkout to your older commit (e4a8ee74396494243c9e7a9df1a3e8d3e27508ad)

Do you have a better solution to this? Thank you🙏

Also would be nice to update your documentation😅✨
![2022-11-28 08_15_03-DominikDoom_a1111-sd-webui-tagcomplete_ Booru style tag autocompletion for AUTOM](https://user-images.githubusercontent.com/64251396/204174298-2325e62f-cedd-4099-bd6f-e416f502fb00.jpg)
It's still there.

**Comment by DominikDoom** [comment]
The webui settings are all saved in the webui root directory, in a file called config.json as well. So you could maybe still use the scripts to edit that file instead. The related settings all start with `tac_` (TagAutoComplete).

Depending on the colab it might also be possible to install the webui on your Google Drive so it remembers the settings and extensions, that would alleviate the need for your manual cloning and settings change entirely. But if you don't want that for storage space reasons, the first way should work like I suggested.

> Also would be nice to update your documentation😅✨
It's still there.

Thanks, I forgot about that part. I only changed the main section where it previously explained the config file.
