### ISSUE TITLE
No longer autocompleting since v1.2.2

### ISSUE THREAD

**Issue by Evil-Dragon** [DominikDoom/a1111-sd-webui-tagcomplete#9]
I can only get autocomplete to work up to v1.2.2 but any version after that never brings anything up. Running the latest version of A111 via git pull on launch.

Not sure if related:
`acConfig.activeIn is undefined TypeError: acConfig.activeIn is undefined
    <anonymous> http://127.0.0.1:7860/:1824
    <anonymous> http://127.0.0.1:7860/:1814
    runCallback http://127.0.0.1:7860/:82
    executeCallbacks http://127.0.0.1:7860/:88
    mutationObserver http://127.0.0.1:7860/:93
    MutationCallback* http://127.0.0.1:7860/:92
    EventListener.handleEvent* http://127.0.0.1:7860/:91
`

**Comment by DominikDoom** [comment]
Are you using the current version of the config?
Newer versions added some new settings, and the error reads like it just can't find that setting key.
Would also match the version since 1.3.0 introduced those activeIn keys to support autocompletion in img2img and negative textboxes.

**Comment by Evil-Dragon** [comment]
If you mean the config file in your script then yes, i've overwritten it from the 1.4.2 release.

**Comment by DominikDoom** [comment]
Hm weird, then the error above shouldn't happen.

Another suggestion: It might be that your browser cached the old config. In the Developer Tools, try checking "Disable cache" under the Network tab and reload the page with the Tools still open. That should ensure it reloads the config.

**Comment by Evil-Dragon** [comment]
Definately a cache issue, disabling cache sorted it out and then I reloaded and it worked. Never even though about caching.
