### ISSUE TITLE
Error: tags\temp\wcet.txt does not exist

### ISSUE THREAD

**Issue by cooperdk** [DominikDoom/a1111-sd-webui-tagcomplete#95]
stable-diffusion-webui-tagcomplete\tags\temp\wcet.txt

**Comment by DominikDoom** [comment]
If this file doesn't exist that means the helper script in `stable-diffusion-webui-tagcomplete\scripts` has either not run or not found your correct installation path.

**Comment by cooperdk** [comment]
I am running locally and have never experienced it before. But I tried removing and re-adding a few times without luck.

I had an issue with another script, but that turned out to be due to a badly programmed dependency (Midas).

**Comment by cooperdk** [comment]
This is becoming more odd.
Turns out the file "wcet.txt" isn't even mentioned in your helper script.

Still, somehow it miraculously solved itself after I once again removed the script and re-added it thru the UI.
So I guess it kind of fixed itself :-)

**Comment by DominikDoom** [comment]
> Turns out the file "wcet.txt" isn't even mentioned in your helper script.

If the javascript requested it and the helper script didn't mention it before you reinstalled it, I'm pretty sure it was a version mismatch. Both were (obviously) introduced in the same update, but it seems like your helper file wasn't updated correctly for some reason.
