### ISSUE TITLE
Syntax tab-suggestions for UmiAI

### ISSUE THREAD

**Issue by ctwrs** [DominikDoom/a1111-sd-webui-tagcomplete#96]
Hi, I'm trying to add convenience syntax completition for Umi tags:
- after `<[tag` -> `'][', '|', ']>', ...filteredWildcards`
- after `<` if Umi is detected suggest `[` as the first thing

I'm fighting with `hideResults()` in `if (fixedTag === null)` and other ifs that match and I'm worried I'll break other suggestions once I find a condition that would allow me to add these suggestions.

I can commit what I have but it's not much, reduce to get yamlTags in shape of `{ [tag]: true, ... }` to check for a match and a conditional array expansion with hardcoded suggestions.

I can carry implementing with a conditional that will not hide suggestions after a tab-completition of a tag.

This is a nice-to-have so no time pressure here or anything. I just started prototyping because I had a free hour and got a bit stuck on `hideResults()` fighting me all the time :P.

https://github.com/ctwrs/a1111-sd-webui-tagcomplete/commit/ce63ea4559129525185cd2e1af7cbac1435aac0c

**Comment by DominikDoom** [comment]
Dunn o if it will help you, but I have the global `hideBlocked` bool for preventing hideResults() if I explicitly don't want it,
I used that to keep normal wildcards open in case the user wants to insert not only the wildcard but one of its stand-ins.

See this part in insetTextAtCursor():
```js
// Hide results after inserting
if (tagType === "wildcardFile") {
    // If it's a wildcard, we want to keep the results open so the user can select another wildcard
    hideBlocked = true;
    autocomplete(textArea, prompt, sanitizedText);
    setTimeout(() => { hideBlocked = false; }, 100);
} else {
    hideResults(textArea);
}
```
