### ISSUE TITLE
<embeddings> stopped working.

### ISSUE THREAD

**Issue by syddharth** [DominikDoom/a1111-sd-webui-tagcomplete#99]
> Exception in thread Thread-74 (get_embeddings):
> Traceback (most recent call last):
>   File "C:\Python310\lib\threading.py", line 1016, in _bootstrap_inner
>     self.run()
>   File "C:\Python310\lib\threading.py", line 953, in run
>     self._target(*self._args, **self._kwargs)
>   File "C:\AI\SD\stable-diffusion-webui\extensions\a1111-sd-webui-tagcomplete\scripts\tag_autocomplete_helper.py", line 92, in get_embeddings
>     while len(sd_hijack.model_hijack.embedding_db.word_embeddings) + len(sd_hijack.model_hijack.embedding_db.skipped_embeddings) < len(embs_in_dir):
> AttributeError: 'EmbeddingDatabase' object has no attribute 'skipped_embeddings'. Did you mean: 'word_embeddings'?
> Reloading modules: modules.ui
> Refreshing Model List
> Restarting Gradio
> Running on local URL:  http://127.0.0.1:7860
> 
> To create a public link, set `share=True` in `launch()`.

It was working a fine till yesterday.

**Comment by DominikDoom** [comment]
Update your webui. skipped_embeddings is a very recent addition to the webui (~1 day ago), but needed for the v1/v2 embedding metadata I added.

**Comment by DominikDoom** [comment]
Glad you find it useful!
To be on the safe side, I'll add a fallback, then it shouldn't stop working on older versions.
At least for now while it's still very recent and many users might not have updated the webui itself yet.
